/** Homepage FAQ: shared by visible accordions and FAQPage JSON-LD */
export type FaqItem = { q: string; a: string };

const EN_FAQS: FaqItem[] = [
  {
    q: "What is Notepad Online?",
    a: "Notepad Online is a browser-based text editor that allows you to write, edit, and manage notes instantly without installing any software. It works on any device, making note-taking simple, fast, and accessible from anywhere.",
  },
  {
    q: "Is Notepad Online free to use?",
    a: "Yes, Notepad Online is completely free to use with no hidden charges or subscriptions. You can create, edit, and store unlimited notes without worrying about usage limits.",
  },
  {
    q: "Do I need to sign up to use Notepad Online?",
    a: "No, you can start using Notepad Online instantly without creating an account or logging in. This makes it quick and hassle-free for users who want immediate access to a text editor.",
  },
  {
    q: "Can I save my notes online?",
    a: "Yes, your notes can be saved online so you can access and continue editing them anytime. This ensures your work is محفوظ and available across different sessions and devices.",
  },
  {
    q: "Does Notepad Online support auto-save?",
    a: "Yes, the editor includes an auto-save feature that continuously saves your notes while you type. This helps prevent data loss in case of accidental refresh, crash, or browser closure.",
  },
  {
    q: "Can I access my notes from different devices?",
    a: "Yes, you can access your saved notes from any device including mobile, tablet, or desktop. All you need is an internet connection to open and edit your notes anytime.",
  },
  {
    q: "Is my data secure on Notepad Online?",
    a: "Yes, your notes are stored securely with privacy-focused measures to keep your content protected. Your data is not publicly shared and remains under your control.",
  },
  {
    q: "Can I share my notes with others?",
    a: "Yes, you can easily share your notes by generating a unique shareable link. This makes collaboration and quick sharing simple without needing additional tools.",
  },
  {
    q: "Does Notepad Online work on mobile devices?",
    a: "Yes, Notepad Online is fully responsive and works smoothly on smartphones and tablets. You can write and edit notes on the go with the same ease as on a desktop.",
  },
  {
    q: "Can I use Notepad Online offline?",
    a: "Some basic features may work offline depending on your browser capabilities. However, an internet connection is recommended for saving, syncing, and accessing your notes reliably.",
  },
  {
    q: "Is Notepad Online better than traditional Notepad or WordPad?",
    a: "Notepad Online offers cloud saving, cross-device access, and sharing features that traditional offline tools do not provide. It gives you more flexibility and convenience for modern note-taking needs.",
  },
  {
    q: "What features does Notepad Online include?",
    a: "Notepad Online includes a clean text editor, auto-save functionality, online storage, and easy note sharing. It is designed to be fast, minimal, and distraction-free for better productivity.",
  },
  {
    q: "Can I use Notepad Online for writing documents?",
    a: "Yes, you can use it to write notes, drafts, articles, or simple documents quickly and efficiently. It is perfect for users who want a lightweight alternative to heavy writing software.",
  },
  {
    q: "Does Notepad Online support formatting?",
    a: "Basic formatting options may be available to help you structure your text clearly. This makes it easier to organize and read your notes compared to plain text editors.",
  },
  {
    q: "How is Notepad Online different from other online editors?",
    a: "Notepad Online focuses on simplicity, speed, and ease of use without unnecessary features. It is ideal for users who want a clean, distraction-free writing experience.",
  },
];

const AR_FAQS: FaqItem[] = [
  { q: "ما هو Notepad Online؟", a: "Notepad Online هو محرر نصوص يعمل في المتصفح ويتيح لك كتابة الملاحظات وتحريرها وحفظها بسرعة بدون تثبيت." },
  { q: "هل Notepad Online مجاني؟", a: "نعم، الخدمة مجانية بالكامل بدون رسوم خفية أو اشتراك، ويمكنك إنشاء وتعديل الملاحظات بسهولة." },
  { q: "هل أحتاج إلى تسجيل حساب لاستخدامه؟", a: "لا، يمكنك البدء فورًا بدون إنشاء حساب أو تسجيل دخول." },
  { q: "هل يمكنني حفظ ملاحظاتي عبر الإنترنت؟", a: "نعم، يمكنك حفظ الملاحظات والعودة لها لاحقًا من أي جهاز." },
  { q: "هل يدعم الحفظ التلقائي؟", a: "نعم، يتم حفظ التغييرات تلقائيًا أثناء الكتابة لتقليل فقدان البيانات." },
  { q: "هل يمكن الوصول للملاحظات من أجهزة مختلفة؟", a: "نعم، يمكنك فتح ملاحظاتك من الهاتف أو الكمبيوتر أو الجهاز اللوحي." },
  { q: "هل بياناتي آمنة؟", a: "نعم، يتم التعامل مع البيانات بإجراءات خصوصية لحماية المحتوى." },
  { q: "هل يمكنني مشاركة ملاحظاتي؟", a: "نعم، يمكنك مشاركة الملاحظات بسهولة عبر رابط قابل للمشاركة." },
  { q: "هل يعمل على الجوال؟", a: "نعم، الموقع متجاوب بالكامل ويعمل بسلاسة على الهواتف." },
  { q: "هل يعمل بدون إنترنت؟", a: "قد تعمل بعض الوظائف الأساسية، لكن الاتصال بالإنترنت أفضل للحفظ والمزامنة." },
  { q: "هل هو أفضل من Notepad أو WordPad التقليدي؟", a: "يوفر ميزات حديثة مثل الحفظ السحابي والمشاركة والوصول من أجهزة متعددة." },
  { q: "ما أهم الميزات المتوفرة؟", a: "تحرير نصوص بسيط، حفظ تلقائي، تخزين، ومشاركة سهلة للملاحظات." },
  { q: "هل يصلح لكتابة المستندات؟", a: "نعم، مناسب للملاحظات والمسودات والمحتوى النصي اليومي." },
  { q: "هل يدعم تنسيق النص؟", a: "تتوفر خيارات أساسية تساعدك على تنظيم النص وقراءته بشكل أفضل." },
  { q: "ما الفرق بينه وبين المحررات الأخرى؟", a: "يركز على السرعة والبساطة وتجربة كتابة بدون تشتيت." },
];

const ES_FAQS: FaqItem[] = [
  { q: "¿Qué es Notepad Online?", a: "Notepad Online es un editor de texto en el navegador para escribir, editar y guardar notas al instante sin instalar nada." },
  { q: "¿Notepad Online es gratis?", a: "Sí, es totalmente gratis y no tiene costos ocultos ni suscripciones." },
  { q: "¿Necesito registrarme para usarlo?", a: "No, puedes empezar de inmediato sin crear cuenta." },
  { q: "¿Puedo guardar mis notas en línea?", a: "Sí, puedes guardar tus notas y volver a editarlas cuando quieras." },
  { q: "¿Tiene guardado automático?", a: "Sí, guarda automáticamente mientras escribes para evitar pérdida de datos." },
  { q: "¿Puedo acceder desde varios dispositivos?", a: "Sí, funciona en móvil, tablet y escritorio." },
  { q: "¿Mis datos están seguros?", a: "Sí, se aplican medidas de privacidad para proteger tu contenido." },
  { q: "¿Puedo compartir mis notas?", a: "Sí, puedes compartirlas fácilmente mediante enlace." },
  { q: "¿Funciona en móviles?", a: "Sí, la interfaz es responsive y funciona bien en smartphones." },
  { q: "¿Funciona sin internet?", a: "Algunas funciones pueden funcionar offline, pero se recomienda conexión para guardar y sincronizar." },
  { q: "¿Es mejor que Notepad o WordPad?", a: "Ofrece ventajas modernas como acceso multiplataforma y compartir notas." },
  { q: "¿Qué funciones incluye?", a: "Editor limpio, auto-guardado, almacenamiento y compartir notas." },
  { q: "¿Sirve para escribir documentos?", a: "Sí, es útil para notas, borradores, artículos y textos rápidos." },
  { q: "¿Admite formato de texto?", a: "Incluye opciones básicas para organizar mejor el contenido." },
  { q: "¿En qué se diferencia de otros editores?", a: "Se centra en simplicidad, velocidad y escritura sin distracciones." },
];

const FR_FAQS: FaqItem[] = [
  { q: "Qu’est-ce que Notepad Online ?", a: "Notepad Online est un éditeur de texte dans le navigateur pour écrire, modifier et enregistrer des notes instantanément." },
  { q: "Notepad Online est-il gratuit ?", a: "Oui, il est entièrement gratuit, sans frais cachés ni abonnement." },
  { q: "Faut-il créer un compte ?", a: "Non, vous pouvez l’utiliser immédiatement sans inscription." },
  { q: "Puis-je enregistrer mes notes en ligne ?", a: "Oui, vos notes peuvent être enregistrées et rouvertes à tout moment." },
  { q: "Y a-t-il une sauvegarde automatique ?", a: "Oui, vos notes se sauvegardent automatiquement pendant la saisie." },
  { q: "Puis-je accéder à mes notes sur plusieurs appareils ?", a: "Oui, depuis mobile, tablette ou ordinateur." },
  { q: "Mes données sont-elles sécurisées ?", a: "Oui, des mesures de confidentialité protègent votre contenu." },
  { q: "Puis-je partager mes notes ?", a: "Oui, vous pouvez partager vos notes via un lien." },
  { q: "Fonctionne-t-il sur mobile ?", a: "Oui, l’interface est responsive et adaptée au mobile." },
  { q: "Puis-je l’utiliser hors ligne ?", a: "Certaines fonctions peuvent marcher hors ligne, mais internet est recommandé pour sauvegarder et synchroniser." },
  { q: "Est-il meilleur que Notepad/WordPad ?", a: "Il offre des fonctions modernes comme l’accès multi-appareils et le partage." },
  { q: "Quelles fonctionnalités sont incluses ?", a: "Éditeur épuré, auto-save, stockage en ligne et partage rapide." },
  { q: "Puis-je écrire des documents avec ?", a: "Oui, pour notes, brouillons et documents simples." },
  { q: "Le formatage est-il pris en charge ?", a: "Des options de base peuvent aider à structurer le texte." },
  { q: "Quelle différence avec d’autres éditeurs ?", a: "Il privilégie la simplicité, la rapidité et une écriture sans distraction." },
];

const DE_FAQS: FaqItem[] = [
  { q: "Was ist Notepad Online?", a: "Notepad Online ist ein browserbasierter Texteditor zum schnellen Schreiben, Bearbeiten und Speichern von Notizen." },
  { q: "Ist Notepad Online kostenlos?", a: "Ja, komplett kostenlos ohne versteckte Gebühren." },
  { q: "Muss ich mich registrieren?", a: "Nein, du kannst sofort ohne Konto starten." },
  { q: "Kann ich meine Notizen online speichern?", a: "Ja, du kannst Notizen speichern und jederzeit weiterbearbeiten." },
  { q: "Gibt es Autosave?", a: "Ja, Änderungen werden automatisch gespeichert." },
  { q: "Kann ich von mehreren Geräten zugreifen?", a: "Ja, von Smartphone, Tablet und Desktop." },
  { q: "Sind meine Daten sicher?", a: "Ja, Datenschutzmaßnahmen schützen deine Inhalte." },
  { q: "Kann ich Notizen teilen?", a: "Ja, per teilbarem Link." },
  { q: "Funktioniert es auf Mobilgeräten?", a: "Ja, die Oberfläche ist mobiloptimiert." },
  { q: "Funktioniert es offline?", a: "Teilweise, aber für zuverlässiges Speichern wird Internet empfohlen." },
  { q: "Besser als Notepad oder WordPad?", a: "Es bietet moderne Funktionen wie Cloud-Speicherung und Gerätezugriff." },
  { q: "Welche Funktionen gibt es?", a: "Klarer Editor, Autosave, Speicherung und Teilen." },
  { q: "Kann ich damit Dokumente schreiben?", a: "Ja, ideal für Notizen, Entwürfe und einfache Texte." },
  { q: "Gibt es Textformatierung?", a: "Grundlegende Formatierung kann verfügbar sein." },
  { q: "Was unterscheidet es von anderen Editoren?", a: "Fokus auf Geschwindigkeit, Einfachheit und ablenkungsfreies Schreiben." },
];

const PT_FAQS: FaqItem[] = [
  { q: "O que é o Notepad Online?", a: "É um editor de texto no navegador para escrever, editar e salvar notas instantaneamente." },
  { q: "O Notepad Online é gratuito?", a: "Sim, é totalmente gratuito, sem custos ocultos." },
  { q: "Preciso criar conta para usar?", a: "Não, você pode começar imediatamente sem cadastro." },
  { q: "Posso salvar minhas notas online?", a: "Sim, suas notas podem ser salvas e acessadas depois." },
  { q: "Existe salvamento automático?", a: "Sim, o conteúdo é salvo automaticamente enquanto você digita." },
  { q: "Posso acessar de diferentes dispositivos?", a: "Sim, em celular, tablet e computador." },
  { q: "Meus dados estão seguros?", a: "Sim, há medidas de privacidade para proteger suas notas." },
  { q: "Posso compartilhar minhas notas?", a: "Sim, via link compartilhável." },
  { q: "Funciona no celular?", a: "Sim, é responsivo e funciona bem em dispositivos móveis." },
  { q: "Posso usar offline?", a: "Alguns recursos podem funcionar offline, mas internet é recomendada para salvar e sincronizar." },
  { q: "É melhor que Notepad/WordPad?", a: "Oferece recursos modernos como acesso em vários dispositivos e compartilhamento." },
  { q: "Quais recursos estão incluídos?", a: "Editor limpo, auto-save, armazenamento e compartilhamento rápido." },
  { q: "Posso escrever documentos?", a: "Sim, para notas, rascunhos e textos simples." },
  { q: "Tem formatação de texto?", a: "Pode incluir opções básicas de formatação." },
  { q: "Qual a diferença para outros editores?", a: "Foco em simplicidade, velocidade e escrita sem distrações." },
];

const ZH_FAQS: FaqItem[] = [
  { q: "什么是 Notepad Online？", a: "Notepad Online 是一款基于浏览器的文本编辑器，无需安装即可快速编写、编辑和保存笔记。" },
  { q: "Notepad Online 是免费的吗？", a: "是的，完全免费使用，没有隐藏费用或订阅要求。" },
  { q: "使用前需要注册吗？", a: "不需要，你可以直接开始使用，无需注册或登录。" },
  { q: "我可以在线保存笔记吗？", a: "可以，笔记可在线保存，方便你随时继续编辑。" },
  { q: "是否支持自动保存？", a: "支持，输入时会自动保存，降低内容丢失风险。" },
  { q: "可以在不同设备访问吗？", a: "可以，手机、平板和电脑都可访问同一份笔记。" },
  { q: "我的数据安全吗？", a: "是的，系统采用隐私保护措施来保护你的内容。" },
  { q: "可以分享笔记吗？", a: "可以，你可以通过分享链接快速发送给他人。" },
  { q: "手机上能用吗？", a: "可以，页面适配移动端，手机使用流畅。" },
  { q: "可以离线使用吗？", a: "部分功能可能可离线使用，但建议联网以获得稳定保存和同步。" },
  { q: "比传统记事本更好吗？", a: "它提供跨设备访问、在线保存和分享等现代功能。" },
  { q: "主要功能有哪些？", a: "包含简洁编辑器、自动保存、在线存储和分享功能。" },
  { q: "可以写文档吗？", a: "可以，适合写笔记、草稿、文章和日常文本。" },
  { q: "支持文本格式吗？", a: "提供基础格式能力，帮助你更清晰地组织内容。" },
  { q: "和其他编辑器有何不同？", a: "重点在速度、简洁和无干扰写作体验。" },
];

const HI_FAQS: FaqItem[] = [
  { q: "Notepad Online क्या है?", a: "Notepad Online एक ब्राउज़र-आधारित टेक्स्ट एडिटर है जिसमें आप बिना इंस्टॉल किए तुरंत लिख, एडिट और सेव कर सकते हैं।" },
  { q: "क्या Notepad Online फ्री है?", a: "हाँ, यह पूरी तरह फ्री है और इसमें कोई छुपा शुल्क नहीं है।" },
  { q: "क्या उपयोग के लिए साइन-अप जरूरी है?", a: "नहीं, आप बिना अकाउंट बनाए तुरंत इस्तेमाल शुरू कर सकते हैं।" },
  { q: "क्या मैं नोट्स ऑनलाइन सेव कर सकता हूँ?", a: "हाँ, नोट्स सेव हो सकते हैं और आप बाद में कभी भी उन्हें खोल सकते हैं।" },
  { q: "क्या इसमें ऑटो-सेव है?", a: "हाँ, टाइप करते समय ऑटो-सेव होता है ताकि डेटा लॉस कम हो।" },
  { q: "क्या मैं अलग-अलग डिवाइस से एक्सेस कर सकता हूँ?", a: "हाँ, मोबाइल, टैबलेट और डेस्कटॉप पर एक्सेस कर सकते हैं।" },
  { q: "क्या मेरा डेटा सुरक्षित है?", a: "हाँ, आपके कंटेंट की सुरक्षा के लिए प्राइवेसी उपाय लागू हैं।" },
  { q: "क्या मैं नोट्स शेयर कर सकता हूँ?", a: "हाँ, शेयर लिंक के जरिए आसानी से नोट्स भेज सकते हैं।" },
  { q: "क्या यह मोबाइल पर काम करता है?", a: "हाँ, यह पूरी तरह responsive है और मोबाइल पर अच्छी तरह काम करता है।" },
  { q: "क्या इसे ऑफलाइन उपयोग कर सकते हैं?", a: "कुछ बेसिक फीचर्स ऑफलाइन चल सकते हैं, लेकिन सेव/सिंक के लिए इंटरनेट बेहतर है।" },
  { q: "क्या यह Notepad या WordPad से बेहतर है?", a: "यह क्लाउड सेव, शेयरिंग और मल्टी-डिवाइस एक्सेस जैसी आधुनिक सुविधाएँ देता है।" },
  { q: "इसमें कौन-कौन से फीचर्स हैं?", a: "क्लीन एडिटर, ऑटो-सेव, ऑनलाइन स्टोरेज और आसान शेयरिंग शामिल हैं।" },
  { q: "क्या मैं इसमें डॉक्यूमेंट लिख सकता हूँ?", a: "हाँ, नोट्स, ड्राफ्ट और साधारण डॉक्यूमेंट के लिए यह उपयुक्त है।" },
  { q: "क्या टेक्स्ट फॉर्मैटिंग सपोर्ट है?", a: "बेसिक फॉर्मैटिंग विकल्प उपलब्ध हो सकते हैं, जिससे टेक्स्ट व्यवस्थित रहता है।" },
  { q: "यह दूसरे एडिटर्स से अलग कैसे है?", a: "यह सादगी, स्पीड और distraction-free writing पर फोकस करता है।" },
];

const RU_FAQS: FaqItem[] = [
  { q: "Что такое Notepad Online?", a: "Notepad Online — это браузерный текстовый редактор для быстрого создания, редактирования и сохранения заметок без установки." },
  { q: "Notepad Online бесплатный?", a: "Да, сервис полностью бесплатный и без скрытых платежей." },
  { q: "Нужна ли регистрация?", a: "Нет, можно начать работу сразу без регистрации и входа." },
  { q: "Можно ли сохранять заметки онлайн?", a: "Да, заметки сохраняются и доступны для дальнейшего редактирования." },
  { q: "Есть ли автосохранение?", a: "Да, заметки сохраняются автоматически во время набора текста." },
  { q: "Можно ли открыть заметки на другом устройстве?", a: "Да, доступ возможен с телефона, планшета и компьютера." },
  { q: "Безопасны ли мои данные?", a: "Да, применяются меры защиты и конфиденциальности данных." },
  { q: "Можно ли делиться заметками?", a: "Да, заметки можно быстро отправить по ссылке." },
  { q: "Работает ли на мобильных устройствах?", a: "Да, интерфейс адаптирован под смартфоны и планшеты." },
  { q: "Работает ли офлайн?", a: "Часть функций может работать офлайн, но для надежного сохранения и синхронизации нужен интернет." },
  { q: "Чем лучше обычного Notepad/WordPad?", a: "Есть современные функции: онлайн-сохранение, доступ с разных устройств и шаринг." },
  { q: "Какие есть функции?", a: "Минималистичный редактор, автосохранение, онлайн-хранение и удобный обмен заметками." },
  { q: "Подходит ли для написания документов?", a: "Да, отлично подходит для заметок, черновиков и простых документов." },
  { q: "Поддерживается ли форматирование?", a: "Доступны базовые возможности форматирования для лучшей структуры текста." },
  { q: "Чем отличается от других редакторов?", a: "Ставка на простоту, скорость и удобную работу без отвлекающих элементов." },
];

const JA_FAQS: FaqItem[] = [
  { q: "Notepad Online とは何ですか？", a: "Notepad Online はブラウザ上で使えるテキストエディタで、インストール不要ですぐにメモの作成・編集・保存ができます。" },
  { q: "Notepad Online は無料ですか？", a: "はい、完全無料で利用でき、隠れた料金はありません。" },
  { q: "利用に登録は必要ですか？", a: "いいえ、アカウント作成やログインなしですぐ使えます。" },
  { q: "メモをオンライン保存できますか？", a: "はい、メモを保存して後でいつでも編集できます。" },
  { q: "自動保存はありますか？", a: "はい、入力中に自動保存されます。" },
  { q: "別の端末からアクセスできますか？", a: "はい、スマホ・タブレット・PCからアクセスできます。" },
  { q: "データは安全ですか？", a: "はい、プライバシーを重視した保護対策が適用されています。" },
  { q: "メモを共有できますか？", a: "はい、共有リンクで簡単に共有できます。" },
  { q: "モバイルでも使えますか？", a: "はい、モバイル対応で快適に使えます。" },
  { q: "オフラインでも使えますか？", a: "一部機能は使える場合がありますが、保存・同期にはネット接続を推奨します。" },
  { q: "Notepad/WordPad より優れていますか？", a: "マルチデバイスアクセスや共有など、より現代的な機能があります。" },
  { q: "主な機能は何ですか？", a: "シンプルなエディタ、自動保存、オンライン保存、共有機能です。" },
  { q: "文書作成にも使えますか？", a: "はい、メモ・下書き・短い文書作成に適しています。" },
  { q: "書式設定はできますか？", a: "基本的な書式設定で読みやすく整理できます。" },
  { q: "他のエディタとの違いは？", a: "シンプルさ、速度、集中しやすい編集体験に特化しています。" },
];

const ID_FAQS: FaqItem[] = [
  { q: "Apa itu Notepad Online?", a: "Notepad Online adalah editor teks berbasis browser untuk menulis, mengedit, dan menyimpan catatan tanpa instalasi." },
  { q: "Apakah Notepad Online gratis?", a: "Ya, sepenuhnya gratis tanpa biaya tersembunyi." },
  { q: "Apakah harus daftar akun?", a: "Tidak, Anda bisa langsung pakai tanpa login." },
  { q: "Bisakah saya menyimpan catatan online?", a: "Ya, catatan bisa disimpan dan dibuka lagi kapan saja." },
  { q: "Apakah ada auto-save?", a: "Ya, perubahan disimpan otomatis saat Anda mengetik." },
  { q: "Bisa diakses dari perangkat berbeda?", a: "Ya, bisa dari HP, tablet, dan desktop." },
  { q: "Apakah data saya aman?", a: "Ya, ada perlindungan privasi untuk menjaga data Anda." },
  { q: "Bisakah saya membagikan catatan?", a: "Ya, Anda bisa membagikan catatan lewat tautan." },
  { q: "Apakah bisa dipakai di mobile?", a: "Ya, tampilannya responsif dan nyaman di ponsel." },
  { q: "Bisa dipakai offline?", a: "Beberapa fitur mungkin bisa, tetapi internet disarankan untuk simpan/sinkron." },
  { q: "Lebih baik dari Notepad/WordPad?", a: "Memiliki fitur modern seperti akses lintas perangkat dan berbagi catatan." },
  { q: "Fitur utamanya apa?", a: "Editor bersih, auto-save, penyimpanan, dan berbagi catatan." },
  { q: "Bisa untuk menulis dokumen?", a: "Ya, cocok untuk catatan, draft, dan dokumen sederhana." },
  { q: "Apakah mendukung formatting?", a: "Ada opsi dasar untuk membantu teks lebih rapi dan mudah dibaca." },
  { q: "Bedanya dengan editor online lain?", a: "Fokus pada kesederhanaan, kecepatan, dan pengalaman tanpa distraksi." },
];

const TR_FAQS: FaqItem[] = [
  { q: "Notepad Online nedir?", a: "Notepad Online, kurulum gerektirmeden not yazma, düzenleme ve kaydetme için tarayıcı tabanlı bir metin editörüdür." },
  { q: "Notepad Online ücretsiz mi?", a: "Evet, tamamen ücretsizdir ve gizli ücret yoktur." },
  { q: "Kullanmak için kayıt gerekli mi?", a: "Hayır, hesap oluşturmadan hemen kullanabilirsiniz." },
  { q: "Notlarımı çevrimiçi kaydedebilir miyim?", a: "Evet, notlarınızı kaydedip daha sonra düzenleyebilirsiniz." },
  { q: "Otomatik kaydetme var mı?", a: "Evet, yazarken otomatik kaydetme yapılır." },
  { q: "Farklı cihazlardan erişebilir miyim?", a: "Evet, telefon, tablet ve bilgisayardan erişebilirsiniz." },
  { q: "Verilerim güvenli mi?", a: "Evet, içerik güvenliği için gizlilik önlemleri uygulanır." },
  { q: "Notlarımı paylaşabilir miyim?", a: "Evet, paylaşım bağlantısıyla notlarınızı gönderebilirsiniz." },
  { q: "Mobilde çalışır mı?", a: "Evet, mobil uyumlu ve akıcı çalışır." },
  { q: "İnternetsiz kullanılabilir mi?", a: "Bazı özellikler çalışabilir, ancak kaydetme/senkron için internet önerilir." },
  { q: "Notepad/WordPad’den daha iyi mi?", a: "Çoklu cihaz erişimi ve paylaşım gibi modern özellikler sunar." },
  { q: "Hangi özellikler var?", a: "Temiz editör, otomatik kaydetme, depolama ve kolay paylaşım." },
  { q: "Belge yazmak için kullanılabilir mi?", a: "Evet, notlar, taslaklar ve basit belgeler için uygundur." },
  { q: "Metin biçimlendirme destekleniyor mu?", a: "Temel biçimlendirme seçenekleriyle metin daha düzenli olur." },
  { q: "Diğer editörlerden farkı ne?", a: "Sadelik, hız ve dikkat dağıtmayan yazım deneyimine odaklanır." },
];

const BN_FAQS: FaqItem[] = [
  { q: "Notepad Online কী?", a: "Notepad Online একটি ব্রাউজার-ভিত্তিক টেক্সট এডিটর, যেখানে ইনস্টল ছাড়াই দ্রুত নোট লিখতে, সম্পাদনা করতে ও সংরক্ষণ করতে পারেন।" },
  { q: "Notepad Online কি ফ্রি?", a: "হ্যাঁ, এটি সম্পূর্ণ ফ্রি এবং কোনো লুকানো চার্জ নেই।" },
  { q: "ব্যবহারের জন্য কি সাইন আপ লাগে?", a: "না, অ্যাকাউন্ট ছাড়া সরাসরি ব্যবহার শুরু করতে পারেন।" },
  { q: "আমি কি নোট অনলাইনে সেভ করতে পারি?", a: "হ্যাঁ, নোট সেভ করে পরে আবার এডিট করতে পারবেন।" },
  { q: "অটো-সেভ আছে কি?", a: "হ্যাঁ, টাইপ করার সময় স্বয়ংক্রিয়ভাবে সেভ হয়।" },
  { q: "ভিন্ন ডিভাইস থেকে অ্যাক্সেস করা যাবে?", a: "হ্যাঁ, মোবাইল, ট্যাব ও ডেস্কটপ থেকে ব্যবহার করা যায়।" },
  { q: "আমার ডেটা কি নিরাপদ?", a: "হ্যাঁ, আপনার কনটেন্ট সুরক্ষায় প্রাইভেসি ব্যবস্থা রয়েছে।" },
  { q: "নোট শেয়ার করা যাবে?", a: "হ্যাঁ, শেয়ার লিংকের মাধ্যমে সহজে শেয়ার করতে পারবেন।" },
  { q: "মোবাইলে কাজ করে?", a: "হ্যাঁ, মোবাইল-ফ্রেন্ডলি এবং স্মুথভাবে কাজ করে।" },
  { q: "অফলাইনে ব্যবহার করা যায়?", a: "কিছু ফিচার কাজ করতে পারে, তবে সেভ/সিঙ্কের জন্য ইন্টারনেট ভালো।" },
  { q: "Notepad/WordPad থেকে ভালো?", a: "এতে মাল্টি-ডিভাইস অ্যাক্সেস ও শেয়ারিংয়ের মতো আধুনিক সুবিধা আছে।" },
  { q: "মূল ফিচার কী কী?", a: "ক্লিন এডিটর, অটো-সেভ, স্টোরেজ এবং সহজ শেয়ারিং।" },
  { q: "ডকুমেন্ট লেখার জন্য ব্যবহার করা যাবে?", a: "হ্যাঁ, নোট, ড্রাফট ও সাধারণ ডকুমেন্টের জন্য উপযোগী।" },
  { q: "টেক্সট ফরম্যাটিং সাপোর্ট আছে?", a: "বেসিক ফরম্যাটিং অপশন থাকতে পারে, যা পড়তে সহজ করে।" },
  { q: "অন্যান্য এডিটর থেকে আলাদা কী?", a: "এটি সরলতা, গতি এবং distraction-free লেখায় ফোকাস করে।" },
];

const UR_FAQS: FaqItem[] = [
  { q: "Notepad Online کیا ہے؟", a: "Notepad Online ایک براؤزر بیسڈ ٹیکسٹ ایڈیٹر ہے جس سے آپ بغیر انسٹالیشن نوٹس لکھ، ایڈٹ اور محفوظ کر سکتے ہیں۔" },
  { q: "کیا Notepad Online مفت ہے؟", a: "جی ہاں، یہ مکمل طور پر مفت ہے اور کوئی پوشیدہ چارج نہیں۔" },
  { q: "کیا استعمال کے لیے سائن اپ ضروری ہے؟", a: "نہیں، آپ بغیر اکاؤنٹ بنائے فوراً استعمال شروع کر سکتے ہیں۔" },
  { q: "کیا میں اپنے نوٹس آن لائن محفوظ کر سکتا ہوں؟", a: "جی ہاں، نوٹس محفوظ ہو جاتے ہیں اور بعد میں دوبارہ ایڈٹ کیے جا سکتے ہیں۔" },
  { q: "کیا آٹو سیو موجود ہے؟", a: "جی ہاں، ٹائپ کرتے وقت مواد خودکار طور پر محفوظ ہوتا رہتا ہے۔" },
  { q: "کیا مختلف ڈیوائسز سے رسائی ممکن ہے؟", a: "جی ہاں، موبائل، ٹیبلٹ اور ڈیسک ٹاپ سے رسائی ممکن ہے۔" },
  { q: "کیا میرا ڈیٹا محفوظ ہے؟", a: "جی ہاں، آپ کے مواد کے تحفظ کے لیے پرائیویسی اقدامات موجود ہیں۔" },
  { q: "کیا میں نوٹس شیئر کر سکتا ہوں؟", a: "جی ہاں، شیئر لنک کے ذریعے آسانی سے شیئر کیا جا سکتا ہے۔" },
  { q: "کیا یہ موبائل پر کام کرتا ہے؟", a: "جی ہاں، یہ موبائل کے لیے مکمل طور پر موزوں ہے۔" },
  { q: "کیا یہ آف لائن چلتا ہے؟", a: "کچھ بنیادی فیچرز چل سکتے ہیں، مگر محفوظ کرنے اور سنک کے لیے انٹرنیٹ بہتر ہے۔" },
  { q: "کیا یہ Notepad/WordPad سے بہتر ہے؟", a: "یہ ملٹی ڈیوائس رسائی اور شیئرنگ جیسی جدید سہولیات فراہم کرتا ہے۔" },
  { q: "اس میں کون سی اہم خصوصیات ہیں؟", a: "کلین ایڈیٹر، آٹو سیو، آن لائن اسٹوریج اور آسان شیئرنگ۔" },
  { q: "کیا میں اس میں دستاویزات لکھ سکتا ہوں؟", a: "جی ہاں، نوٹس، ڈرافٹس اور سادہ دستاویزات کے لیے موزوں ہے۔" },
  { q: "کیا ٹیکسٹ فارمیٹنگ سپورٹ ہے؟", a: "بنیادی فارمیٹنگ آپشنز دستیاب ہو سکتے ہیں۔" },
  { q: "یہ دوسرے ایڈیٹرز سے کیسے مختلف ہے؟", a: "یہ سادگی، رفتار اور بغیر خلل لکھنے کے تجربے پر فوکس کرتا ہے۔" },
];

const KO_FAQS: FaqItem[] = [
  { q: "Notepad Online이란 무엇인가요?", a: "Notepad Online은 설치 없이 브라우저에서 메모를 작성, 편집, 저장할 수 있는 텍스트 편집기입니다." },
  { q: "Notepad Online은 무료인가요?", a: "네, 완전히 무료이며 숨겨진 비용이 없습니다." },
  { q: "사용하려면 회원가입이 필요한가요?", a: "아니요, 로그인 없이 바로 사용할 수 있습니다." },
  { q: "메모를 온라인에 저장할 수 있나요?", a: "네, 메모를 저장하고 나중에 다시 열어 편집할 수 있습니다." },
  { q: "자동 저장을 지원하나요?", a: "네, 입력 중 자동으로 저장됩니다." },
  { q: "다른 기기에서도 접근할 수 있나요?", a: "네, 모바일, 태블릿, 데스크톱에서 모두 사용할 수 있습니다." },
  { q: "내 데이터는 안전한가요?", a: "네, 콘텐츠 보호를 위한 개인정보 보호 조치가 적용됩니다." },
  { q: "메모를 공유할 수 있나요?", a: "네, 공유 링크로 쉽게 전달할 수 있습니다." },
  { q: "모바일에서도 동작하나요?", a: "네, 모바일 환경에 최적화되어 있습니다." },
  { q: "오프라인으로도 사용할 수 있나요?", a: "일부 기능은 가능할 수 있으나 저장/동기화에는 인터넷 연결을 권장합니다." },
  { q: "기존 Notepad/WordPad보다 좋은가요?", a: "다중 기기 접근, 공유 등 현대적인 기능을 제공합니다." },
  { q: "주요 기능은 무엇인가요?", a: "깔끔한 편집기, 자동 저장, 온라인 저장, 쉬운 공유 기능입니다." },
  { q: "문서 작성에도 사용할 수 있나요?", a: "네, 메모, 초안, 간단한 문서 작성에 적합합니다." },
  { q: "텍스트 서식을 지원하나요?", a: "기본 서식 옵션으로 텍스트 정리를 도와줍니다." },
  { q: "다른 편집기와의 차이는 무엇인가요?", a: "단순함, 속도, 방해 없는 작성 경험에 집중합니다." },
];

const VI_FAQS: FaqItem[] = [
  { q: "Notepad Online là gì?", a: "Notepad Online là trình soạn thảo văn bản trên trình duyệt, cho phép viết, chỉnh sửa và lưu ghi chú mà không cần cài đặt." },
  { q: "Notepad Online có miễn phí không?", a: "Có, hoàn toàn miễn phí và không có phí ẩn." },
  { q: "Có cần đăng ký để sử dụng không?", a: "Không, bạn có thể dùng ngay mà không cần tài khoản." },
  { q: "Tôi có thể lưu ghi chú trực tuyến không?", a: "Có, ghi chú có thể lưu lại để bạn mở và chỉnh sửa sau." },
  { q: "Có tự động lưu không?", a: "Có, nội dung được tự động lưu khi bạn nhập." },
  { q: "Có dùng được trên nhiều thiết bị không?", a: "Có, dùng tốt trên điện thoại, máy tính bảng và máy tính." },
  { q: "Dữ liệu của tôi có an toàn không?", a: "Có, dữ liệu được bảo vệ bằng các biện pháp quyền riêng tư." },
  { q: "Tôi có thể chia sẻ ghi chú không?", a: "Có, bạn có thể chia sẻ nhanh bằng liên kết." },
  { q: "Có hoạt động trên di động không?", a: "Có, giao diện responsive và mượt trên di động." },
  { q: "Có thể dùng offline không?", a: "Một số tính năng có thể hoạt động offline, nhưng nên có internet để lưu và đồng bộ." },
  { q: "Có tốt hơn Notepad/WordPad truyền thống không?", a: "Nó có các tính năng hiện đại như lưu trực tuyến, truy cập đa thiết bị và chia sẻ." },
  { q: "Những tính năng chính là gì?", a: "Trình soạn thảo gọn nhẹ, tự động lưu, lưu trữ online và chia sẻ dễ dàng." },
  { q: "Có thể viết tài liệu không?", a: "Có, phù hợp cho ghi chú, bản nháp và tài liệu đơn giản." },
  { q: "Có hỗ trợ định dạng văn bản không?", a: "Có thể có các tùy chọn định dạng cơ bản để nội dung dễ đọc hơn." },
  { q: "Khác gì so với trình soạn thảo khác?", a: "Tập trung vào sự đơn giản, tốc độ và trải nghiệm viết không xao nhãng." },
];

const IT_FAQS: FaqItem[] = [
  { q: "Cos’è Notepad Online?", a: "Notepad Online è un editor di testo nel browser per scrivere, modificare e salvare note senza installazione." },
  { q: "Notepad Online è gratuito?", a: "Sì, è completamente gratuito e senza costi nascosti." },
  { q: "Serve registrarsi per usarlo?", a: "No, puoi iniziare subito senza account." },
  { q: "Posso salvare le note online?", a: "Sì, le note possono essere salvate e riaperte quando vuoi." },
  { q: "Supporta il salvataggio automatico?", a: "Sì, salva automaticamente mentre scrivi." },
  { q: "Posso accedere da dispositivi diversi?", a: "Sì, da smartphone, tablet e desktop." },
  { q: "I miei dati sono al sicuro?", a: "Sì, sono applicate misure di privacy per proteggere i contenuti." },
  { q: "Posso condividere le note?", a: "Sì, puoi condividerle tramite link." },
  { q: "Funziona su mobile?", a: "Sì, è responsive e ottimizzato per il mobile." },
  { q: "Funziona offline?", a: "Alcune funzioni possono funzionare offline, ma internet è consigliato per salvataggio e sincronizzazione." },
  { q: "È meglio di Notepad/WordPad?", a: "Offre funzioni moderne come accesso multi-dispositivo e condivisione." },
  { q: "Quali funzioni include?", a: "Editor pulito, auto-save, archiviazione online e condivisione facile." },
  { q: "Posso scrivere documenti?", a: "Sì, è adatto per note, bozze e documenti semplici." },
  { q: "Supporta la formattazione del testo?", a: "Possono essere disponibili opzioni di formattazione base." },
  { q: "In cosa è diverso dagli altri editor?", a: "Punta su semplicità, velocità e scrittura senza distrazioni." },
];

const FA_FAQS: FaqItem[] = [
  { q: "Notepad Online چیست؟", a: "Notepad Online یک ویرایشگر متن مبتنی بر مرورگر است که بدون نصب، امکان نوشتن، ویرایش و ذخیره یادداشت را می‌دهد." },
  { q: "آیا Notepad Online رایگان است؟", a: "بله، کاملاً رایگان است و هزینه پنهان ندارد." },
  { q: "برای استفاده نیاز به ثبت‌نام دارم؟", a: "خیر، بدون ساخت حساب می‌توانید فوراً استفاده کنید." },
  { q: "آیا می‌توانم یادداشت‌ها را آنلاین ذخیره کنم؟", a: "بله، یادداشت‌ها ذخیره می‌شوند و بعداً قابل ویرایش هستند." },
  { q: "آیا ذخیره خودکار دارد؟", a: "بله، هنگام تایپ به‌صورت خودکار ذخیره می‌شود." },
  { q: "آیا از دستگاه‌های مختلف قابل دسترسی است؟", a: "بله، روی موبایل، تبلت و دسکتاپ در دسترس است." },
  { q: "آیا داده‌های من امن هستند؟", a: "بله، برای حفاظت از محتوا، اقدامات حریم خصوصی اعمال می‌شود." },
  { q: "آیا می‌توانم یادداشت‌ها را به اشتراک بگذارم؟", a: "بله، با لینک اشتراک‌گذاری به‌راحتی قابل ارسال است." },
  { q: "آیا روی موبایل کار می‌کند؟", a: "بله، رابط کاربری واکنش‌گرا و مناسب موبایل است." },
  { q: "آیا آفلاین هم کار می‌کند؟", a: "برخی قابلیت‌ها ممکن است آفلاین کار کنند، اما برای ذخیره و همگام‌سازی اینترنت توصیه می‌شود." },
  { q: "آیا از Notepad/WordPad بهتر است؟", a: "امکانات مدرن‌تری مانند دسترسی چند دستگاهی و اشتراک‌گذاری ارائه می‌دهد." },
  { q: "چه قابلیت‌هایی دارد؟", a: "ویرایشگر ساده، ذخیره خودکار، ذخیره‌سازی آنلاین و اشتراک‌گذاری آسان." },
  { q: "آیا برای نوشتن سند مناسب است؟", a: "بله، برای یادداشت، پیش‌نویس و اسناد ساده مناسب است." },
  { q: "آیا قالب‌بندی متن پشتیبانی می‌شود؟", a: "گزینه‌های پایه قالب‌بندی برای خوانایی بهتر ممکن است در دسترس باشند." },
  { q: "تفاوت آن با سایر ادیتورها چیست؟", a: "روی سادگی، سرعت و تجربه نوشتن بدون حواس‌پرتی تمرکز دارد." },
];

const TH_FAQS: FaqItem[] = [
  { q: "Notepad Online คืออะไร?", a: "Notepad Online คือโปรแกรมแก้ไขข้อความบนเบราว์เซอร์ที่ให้คุณเขียน แก้ไข และบันทึกโน้ตได้ทันทีโดยไม่ต้องติดตั้ง" },
  { q: "Notepad Online ใช้งานฟรีไหม?", a: "ฟรีทั้งหมด และไม่มีค่าใช้จ่ายแอบแฝง" },
  { q: "ต้องสมัครสมาชิกก่อนใช้งานไหม?", a: "ไม่ต้อง คุณเริ่มใช้งานได้ทันทีโดยไม่ต้องล็อกอิน" },
  { q: "บันทึกโน้ตออนไลน์ได้ไหม?", a: "ได้ คุณสามารถบันทึกและกลับมาแก้ไขภายหลังได้" },
  { q: "มีการบันทึกอัตโนมัติไหม?", a: "มี ระบบจะบันทึกให้อัตโนมัติระหว่างพิมพ์" },
  { q: "เข้าถึงจากหลายอุปกรณ์ได้ไหม?", a: "ได้ ใช้ได้ทั้งมือถือ แท็บเล็ต และคอมพิวเตอร์" },
  { q: "ข้อมูลปลอดภัยไหม?", a: "ปลอดภัย มีมาตรการด้านความเป็นส่วนตัวเพื่อปกป้องข้อมูลของคุณ" },
  { q: "แชร์โน้ตได้ไหม?", a: "ได้ สามารถแชร์ผ่านลิงก์ได้อย่างง่ายดาย" },
  { q: "ใช้งานบนมือถือได้ไหม?", a: "ได้ หน้าเว็บรองรับมือถือเต็มรูปแบบ" },
  { q: "ใช้งานออฟไลน์ได้ไหม?", a: "บางฟีเจอร์อาจใช้งานได้ แต่แนะนำให้ต่ออินเทอร์เน็ตเพื่อบันทึกและซิงก์" },
  { q: "ดีกว่า Notepad/WordPad แบบเดิมไหม?", a: "มีฟีเจอร์สมัยใหม่ เช่น เข้าถึงหลายอุปกรณ์และแชร์ได้ง่าย" },
  { q: "มีฟีเจอร์อะไรบ้าง?", a: "มีตัวแก้ไขที่เรียบง่าย บันทึกอัตโนมัติ พื้นที่เก็บข้อมูลออนไลน์ และการแชร์" },
  { q: "ใช้เขียนเอกสารได้ไหม?", a: "ได้ เหมาะกับโน้ต ร่างงาน และเอกสารทั่วไป" },
  { q: "รองรับการจัดรูปแบบข้อความไหม?", a: "มีตัวเลือกพื้นฐานเพื่อช่วยจัดข้อความให้อ่านง่ายขึ้น" },
  { q: "ต่างจากตัวแก้ไขอื่นอย่างไร?", a: "เน้นความเรียบง่าย ความเร็ว และการเขียนแบบไม่ถูกรบกวน" },
];

const NL_FAQS: FaqItem[] = [
  { q: "Wat is Notepad Online?", a: "Notepad Online is een browsergebaseerde teksteditor om direct notities te schrijven, bewerken en opslaan zonder installatie." },
  { q: "Is Notepad Online gratis?", a: "Ja, volledig gratis zonder verborgen kosten." },
  { q: "Moet ik me registreren?", a: "Nee, je kunt direct starten zonder account." },
  { q: "Kan ik notities online opslaan?", a: "Ja, je notities kunnen worden opgeslagen en later opnieuw geopend." },
  { q: "Is er automatisch opslaan?", a: "Ja, tijdens het typen wordt automatisch opgeslagen." },
  { q: "Kan ik op meerdere apparaten werken?", a: "Ja, op mobiel, tablet en desktop." },
  { q: "Zijn mijn gegevens veilig?", a: "Ja, er zijn privacymaatregelen om je content te beschermen." },
  { q: "Kan ik notities delen?", a: "Ja, via een deelbare link." },
  { q: "Werkt het op mobiel?", a: "Ja, de interface is volledig responsive." },
  { q: "Werkt het offline?", a: "Sommige functies mogelijk wel, maar internet wordt aanbevolen voor opslaan en synchroniseren." },
  { q: "Beter dan Notepad/WordPad?", a: "Het biedt moderne functies zoals delen en toegang vanaf meerdere apparaten." },
  { q: "Welke functies zijn inbegrepen?", a: "Een schone editor, auto-save, online opslag en eenvoudig delen." },
  { q: "Kan ik er documenten mee schrijven?", a: "Ja, geschikt voor notities, concepten en eenvoudige documenten." },
  { q: "Ondersteunt het tekstopmaak?", a: "Basale opmaakopties kunnen beschikbaar zijn." },
  { q: "Wat is het verschil met andere editors?", a: "Focus op eenvoud, snelheid en schrijven zonder afleiding." },
];

const SV_FAQS: FaqItem[] = [
  { q: "Vad är Notepad Online?", a: "Notepad Online är en webbläsarbaserad textredigerare för att snabbt skriva, redigera och spara anteckningar utan installation." },
  { q: "Är Notepad Online gratis?", a: "Ja, helt gratis utan dolda avgifter." },
  { q: "Behöver jag registrera mig?", a: "Nej, du kan börja direkt utan konto." },
  { q: "Kan jag spara anteckningar online?", a: "Ja, anteckningar kan sparas och öppnas igen senare." },
  { q: "Finns autospar?", a: "Ja, innehållet sparas automatiskt medan du skriver." },
  { q: "Kan jag komma åt från olika enheter?", a: "Ja, från mobil, surfplatta och dator." },
  { q: "Är mina data säkra?", a: "Ja, integritetsåtgärder används för att skydda ditt innehåll." },
  { q: "Kan jag dela mina anteckningar?", a: "Ja, via delningslänk." },
  { q: "Fungerar det på mobil?", a: "Ja, gränssnittet är mobilanpassat." },
  { q: "Fungerar det offline?", a: "Vissa funktioner kan fungera, men internet rekommenderas för sparning och synk." },
  { q: "Bättre än Notepad/WordPad?", a: "Det erbjuder modernare funktioner som delning och åtkomst från flera enheter." },
  { q: "Vilka funktioner ingår?", a: "Ren editor, autospar, online-lagring och enkel delning." },
  { q: "Kan jag skriva dokument?", a: "Ja, bra för anteckningar, utkast och enkla dokument." },
  { q: "Stödjer den textformatering?", a: "Grundläggande formateringsalternativ kan finnas tillgängliga." },
  { q: "Vad skiljer den från andra editorer?", a: "Fokus på enkelhet, hastighet och distraktionsfri skrivning." },
];

const PL_FAQS: FaqItem[] = [
  { q: "Czym jest Notepad Online?", a: "Notepad Online to edytor tekstu w przeglądarce, który pozwala szybko pisać, edytować i zapisywać notatki bez instalacji." },
  { q: "Czy Notepad Online jest darmowy?", a: "Tak, jest całkowicie darmowy i bez ukrytych opłat." },
  { q: "Czy muszę zakładać konto?", a: "Nie, możesz zacząć od razu bez rejestracji." },
  { q: "Czy mogę zapisywać notatki online?", a: "Tak, notatki można zapisać i wrócić do nich później." },
  { q: "Czy jest autosave?", a: "Tak, treść zapisuje się automatycznie podczas pisania." },
  { q: "Czy działa na różnych urządzeniach?", a: "Tak, na telefonie, tablecie i komputerze." },
  { q: "Czy moje dane są bezpieczne?", a: "Tak, stosowane są mechanizmy prywatności chroniące treść." },
  { q: "Czy mogę udostępniać notatki?", a: "Tak, przez link do udostępniania." },
  { q: "Czy działa na telefonie?", a: "Tak, interfejs jest responsywny i mobilny." },
  { q: "Czy działa offline?", a: "Niektóre funkcje mogą działać, ale internet jest zalecany do zapisu i synchronizacji." },
  { q: "Czy jest lepszy od Notepad/WordPad?", a: "Oferuje nowoczesne funkcje, np. dostęp z wielu urządzeń i udostępnianie." },
  { q: "Jakie funkcje zawiera?", a: "Czysty edytor, autozapis, przechowywanie online i szybkie udostępnianie." },
  { q: "Czy nadaje się do pisania dokumentów?", a: "Tak, do notatek, szkiców i prostych dokumentów." },
  { q: "Czy obsługuje formatowanie tekstu?", a: "Dostępne mogą być podstawowe opcje formatowania." },
  { q: "Czym różni się od innych edytorów?", a: "Stawia na prostotę, szybkość i pisanie bez rozpraszania." },
];

const CS_FAQS: FaqItem[] = [
  { q: "Co je Notepad Online?", a: "Notepad Online je textový editor v prohlížeči pro rychlé psaní, úpravu a ukládání poznámek bez instalace." },
  { q: "Je Notepad Online zdarma?", a: "Ano, je zcela zdarma bez skrytých poplatků." },
  { q: "Musím se registrovat?", a: "Ne, můžete začít ihned bez účtu." },
  { q: "Mohu ukládat poznámky online?", a: "Ano, poznámky lze ukládat a později znovu otevřít." },
  { q: "Má automatické ukládání?", a: "Ano, obsah se ukládá automaticky během psaní." },
  { q: "Lze přistupovat z různých zařízení?", a: "Ano, z mobilu, tabletu i počítače." },
  { q: "Jsou moje data v bezpečí?", a: "Ano, používají se opatření na ochranu soukromí." },
  { q: "Mohu poznámky sdílet?", a: "Ano, snadno přes sdílecí odkaz." },
  { q: "Funguje na mobilu?", a: "Ano, rozhraní je plně responzivní." },
  { q: "Funguje offline?", a: "Některé funkce mohou fungovat, ale internet je doporučen pro ukládání a synchronizaci." },
  { q: "Je lepší než Notepad/WordPad?", a: "Nabízí moderní funkce jako sdílení a přístup z více zařízení." },
  { q: "Jaké funkce obsahuje?", a: "Čistý editor, auto-save, online úložiště a snadné sdílení." },
  { q: "Mohu v něm psát dokumenty?", a: "Ano, hodí se na poznámky, koncepty i jednoduché dokumenty." },
  { q: "Podporuje formátování textu?", a: "Mohou být dostupné základní možnosti formátování." },
  { q: "Čím se liší od jiných editorů?", a: "Zaměřuje se na jednoduchost, rychlost a nerušené psaní." },
];

const RO_FAQS: FaqItem[] = [
  { q: "Ce este Notepad Online?", a: "Notepad Online este un editor text în browser pentru scriere, editare și salvare rapidă fără instalare." },
  { q: "Notepad Online este gratuit?", a: "Da, este complet gratuit și fără costuri ascunse." },
  { q: "Trebuie să îmi fac cont?", a: "Nu, îl poți folosi imediat fără înregistrare." },
  { q: "Pot salva notițele online?", a: "Da, notițele se salvează și pot fi redeschise oricând." },
  { q: "Are salvare automată?", a: "Da, conținutul se salvează automat în timpul tastării." },
  { q: "Pot accesa de pe mai multe dispozitive?", a: "Da, de pe mobil, tabletă și desktop." },
  { q: "Datele mele sunt în siguranță?", a: "Da, se folosesc măsuri de confidențialitate pentru protecția conținutului." },
  { q: "Pot partaja notițele?", a: "Da, prin link de partajare." },
  { q: "Funcționează pe mobil?", a: "Da, interfața este responsive și optimizată." },
  { q: "Funcționează offline?", a: "Unele funcții pot merge offline, dar internetul este recomandat pentru salvare și sincronizare." },
  { q: "Este mai bun decât Notepad/WordPad?", a: "Oferă funcții moderne precum acces multi-device și partajare." },
  { q: "Ce funcții include?", a: "Editor curat, auto-save, stocare online și partajare rapidă." },
  { q: "Pot scrie documente în el?", a: "Da, este potrivit pentru notițe, drafturi și documente simple." },
  { q: "Suportă formatarea textului?", a: "Pot exista opțiuni de formatare de bază." },
  { q: "Cum diferă de alte editoare?", a: "Se concentrează pe simplitate, viteză și scriere fără distrageri." },
];

const HU_FAQS: FaqItem[] = [
  { q: "Mi az a Notepad Online?", a: "A Notepad Online egy böngészőben futó szövegszerkesztő, amellyel telepítés nélkül írhatsz, szerkeszthetsz és menthetsz jegyzeteket." },
  { q: "Ingyenes a Notepad Online?", a: "Igen, teljesen ingyenes, rejtett díjak nélkül." },
  { q: "Kell regisztráció a használathoz?", a: "Nem, azonnal használhatod fiók nélkül." },
  { q: "Menthetem a jegyzeteimet online?", a: "Igen, a jegyzetek menthetők és később bármikor elérhetők." },
  { q: "Van automatikus mentés?", a: "Igen, gépelés közben automatikusan ment." },
  { q: "Elérhető több eszközről is?", a: "Igen, mobilról, tabletről és asztali gépről is." },
  { q: "Biztonságban vannak az adataim?", a: "Igen, adatvédelmi intézkedések védik a tartalmat." },
  { q: "Megoszthatom a jegyzeteimet?", a: "Igen, megosztási linken keresztül." },
  { q: "Működik mobilon?", a: "Igen, mobilbarát és reszponzív." },
  { q: "Működik offline?", a: "Néhány funkció igen, de mentéshez és szinkronhoz internet ajánlott." },
  { q: "Jobb, mint a Notepad/WordPad?", a: "Modern funkciókat ad, például többeszközös elérést és megosztást." },
  { q: "Milyen funkciókat tartalmaz?", a: "Letisztult szerkesztő, auto-save, online tárolás és gyors megosztás." },
  { q: "Lehet vele dokumentumot írni?", a: "Igen, jegyzetekhez, vázlatokhoz és egyszerű dokumentumokhoz ideális." },
  { q: "Támogat szövegformázást?", a: "Alapvető formázási lehetőségek elérhetők lehetnek." },
  { q: "Miben más, mint más editorok?", a: "Az egyszerűségre, sebességre és zavaró elemek nélküli írásra fókuszál." },
];

const HE_FAQS: FaqItem[] = [
  { q: "מה זה Notepad Online?", a: "Notepad Online הוא עורך טקסט מבוסס דפדפן שמאפשר כתיבה, עריכה ושמירה מהירה בלי התקנה." },
  { q: "האם Notepad Online חינמי?", a: "כן, הוא חינמי לחלוטין וללא עלויות נסתרות." },
  { q: "צריך להירשם כדי להשתמש?", a: "לא, אפשר להתחיל מיד בלי חשבון." },
  { q: "אפשר לשמור פתקים אונליין?", a: "כן, אפשר לשמור ולחזור לערוך בכל זמן." },
  { q: "יש שמירה אוטומטית?", a: "כן, התוכן נשמר אוטומטית בזמן ההקלדה." },
  { q: "אפשר לגשת מכמה מכשירים?", a: "כן, ממובייל, טאבלט ומחשב." },
  { q: "הנתונים שלי מאובטחים?", a: "כן, יש אמצעי פרטיות להגנה על התוכן שלך." },
  { q: "אפשר לשתף פתקים?", a: "כן, באמצעות קישור שיתוף." },
  { q: "זה עובד במובייל?", a: "כן, הממשק מותאם לנייד." },
  { q: "אפשר להשתמש אופליין?", a: "חלק מהיכולות עשויות לעבוד, אך אינטרנט מומלץ לשמירה וסנכרון." },
  { q: "זה עדיף על Notepad/WordPad?", a: "יש בו יכולות מודרניות כמו גישה מרובת מכשירים ושיתוף." },
  { q: "אילו פיצ'רים יש?", a: "עורך נקי, שמירה אוטומטית, אחסון אונליין ושיתוף מהיר." },
  { q: "אפשר לכתוב מסמכים?", a: "כן, מתאים לפתקים, טיוטות ומסמכים פשוטים." },
  { q: "יש תמיכה בעיצוב טקסט?", a: "עשויות להיות אפשרויות עיצוב בסיסיות." },
  { q: "מה ההבדל מול עורכים אחרים?", a: "התמקדות בפשטות, מהירות וכתיבה ללא הסחות דעת." },
];

const DA_FAQS: FaqItem[] = [
  { q: "Hvad er Notepad Online?", a: "Notepad Online er en browserbaseret teksteditor til hurtig skrivning, redigering og gemning af noter uden installation." },
  { q: "Er Notepad Online gratis?", a: "Ja, helt gratis uden skjulte omkostninger." },
  { q: "Skal jeg oprette en konto?", a: "Nej, du kan starte med det samme uden login." },
  { q: "Kan jeg gemme noter online?", a: "Ja, noter kan gemmes og åbnes igen senere." },
  { q: "Har den autosave?", a: "Ja, den gemmer automatisk mens du skriver." },
  { q: "Kan jeg få adgang fra flere enheder?", a: "Ja, fra mobil, tablet og desktop." },
  { q: "Er mine data sikre?", a: "Ja, der bruges privatlivsforanstaltninger til at beskytte dit indhold." },
  { q: "Kan jeg dele mine noter?", a: "Ja, via delbart link." },
  { q: "Virker den på mobil?", a: "Ja, den er mobilvenlig og responsiv." },
  { q: "Virker den offline?", a: "Nogle funktioner kan virke offline, men internet anbefales til gem/synk." },
  { q: "Er den bedre end Notepad/WordPad?", a: "Den giver moderne funktioner som deling og adgang på tværs af enheder." },
  { q: "Hvilke funktioner er inkluderet?", a: "Ren editor, autosave, online lagring og nem deling." },
  { q: "Kan jeg skrive dokumenter?", a: "Ja, velegnet til noter, kladder og simple dokumenter." },
  { q: "Understøtter den formatering?", a: "Grundlæggende formateringsmuligheder kan være tilgængelige." },
  { q: "Hvordan adskiller den sig fra andre editorer?", a: "Fokus på enkelhed, hastighed og distraktionsfri skrivning." },
];

const FI_FAQS: FaqItem[] = [
  { q: "Mikä on Notepad Online?", a: "Notepad Online on selaimessa toimiva tekstieditori, jolla voit kirjoittaa, muokata ja tallentaa muistiinpanoja ilman asennusta." },
  { q: "Onko Notepad Online ilmainen?", a: "Kyllä, täysin ilmainen ilman piilokuluja." },
  { q: "Tarvitaanko rekisteröitymistä?", a: "Ei, voit aloittaa heti ilman tiliä." },
  { q: "Voinko tallentaa muistiinpanot verkkoon?", a: "Kyllä, muistiinpanot voi tallentaa ja avata myöhemmin uudelleen." },
  { q: "Onko automaattitallennus?", a: "Kyllä, sisältö tallentuu automaattisesti kirjoittaessa." },
  { q: "Voinko käyttää eri laitteilla?", a: "Kyllä, mobiililla, tabletilla ja tietokoneella." },
  { q: "Ovatko tietoni turvassa?", a: "Kyllä, sisältöä suojataan tietosuoja-käytännöillä." },
  { q: "Voinko jakaa muistiinpanot?", a: "Kyllä, jaettavan linkin avulla." },
  { q: "Toimiiko mobiilissa?", a: "Kyllä, käyttöliittymä on mobiiliystävällinen." },
  { q: "Toimiiko offline-tilassa?", a: "Osa toiminnoista voi toimia, mutta internetiä suositellaan tallennukseen ja synkronointiin." },
  { q: "Parempi kuin Notepad/WordPad?", a: "Tarjoaa moderneja ominaisuuksia, kuten monilaitekäytön ja jakamisen." },
  { q: "Mitä ominaisuuksia mukana on?", a: "Selkeä editori, automaattitallennus, verkkotallennus ja helppo jakaminen." },
  { q: "Voiko sillä kirjoittaa dokumentteja?", a: "Kyllä, sopii muistiinpanoihin, luonnoksiin ja yksinkertaisiin dokumentteihin." },
  { q: "Tukeeko tekstin muotoilua?", a: "Perusmuotoilu voi olla käytettävissä." },
  { q: "Miten se eroaa muista editoreista?", a: "Painottaa yksinkertaisuutta, nopeutta ja häiriötöntä kirjoittamista." },
];

const NO_FAQS: FaqItem[] = [
  { q: "Hva er Notepad Online?", a: "Notepad Online er en nettleserbasert teksteditor for rask skriving, redigering og lagring uten installasjon." },
  { q: "Er Notepad Online gratis?", a: "Ja, helt gratis uten skjulte kostnader." },
  { q: "Må jeg registrere meg?", a: "Nei, du kan starte med en gang uten konto." },
  { q: "Kan jeg lagre notater på nett?", a: "Ja, notater kan lagres og åpnes igjen senere." },
  { q: "Har den automatisk lagring?", a: "Ja, innhold lagres automatisk mens du skriver." },
  { q: "Kan jeg bruke den på flere enheter?", a: "Ja, på mobil, nettbrett og desktop." },
  { q: "Er dataene mine trygge?", a: "Ja, personverntiltak beskytter innholdet ditt." },
  { q: "Kan jeg dele notater?", a: "Ja, via delbar lenke." },
  { q: "Fungerer den på mobil?", a: "Ja, den er responsiv og mobilvennlig." },
  { q: "Fungerer den offline?", a: "Noen funksjoner kan fungere, men internett anbefales for lagring og synkronisering." },
  { q: "Er den bedre enn Notepad/WordPad?", a: "Den tilbyr moderne funksjoner som deling og tilgang på tvers av enheter." },
  { q: "Hvilke funksjoner finnes?", a: "Ren editor, autosave, nettlagring og enkel deling." },
  { q: "Kan jeg skrive dokumenter?", a: "Ja, egnet for notater, utkast og enkle dokumenter." },
  { q: "Støtter den tekstformatering?", a: "Grunnleggende formateringsvalg kan være tilgjengelige." },
  { q: "Hva skiller den fra andre editorer?", a: "Fokus på enkelhet, hastighet og distraksjonsfri skriving." },
];

const SK_FAQS: FaqItem[] = [
  { q: "Čo je Notepad Online?", a: "Notepad Online je textový editor v prehliadači na rýchle písanie, úpravu a ukladanie poznámok bez inštalácie." },
  { q: "Je Notepad Online zadarmo?", a: "Áno, je úplne zadarmo bez skrytých poplatkov." },
  { q: "Musím sa registrovať?", a: "Nie, môžete začať hneď bez účtu." },
  { q: "Môžem ukladať poznámky online?", a: "Áno, poznámky môžete ukladať a neskôr znova otvoriť." },
  { q: "Má automatické ukladanie?", a: "Áno, obsah sa počas písania ukladá automaticky." },
  { q: "Dá sa používať na viacerých zariadeniach?", a: "Áno, na mobile, tablete aj počítači." },
  { q: "Sú moje dáta bezpečné?", a: "Áno, používajú sa opatrenia na ochranu súkromia." },
  { q: "Môžem poznámky zdieľať?", a: "Áno, cez zdieľateľný odkaz." },
  { q: "Funguje na mobile?", a: "Áno, je plne responzívny." },
  { q: "Funguje offline?", a: "Niektoré funkcie môžu fungovať, no internet sa odporúča pre uloženie a synchronizáciu." },
  { q: "Je lepší ako Notepad/WordPad?", a: "Ponúka moderné funkcie ako prístup z viacerých zariadení a zdieľanie." },
  { q: "Aké funkcie obsahuje?", a: "Čistý editor, auto-save, online úložisko a jednoduché zdieľanie." },
  { q: "Môžem v ňom písať dokumenty?", a: "Áno, je vhodný na poznámky, koncepty a jednoduché dokumenty." },
  { q: "Podporuje formátovanie textu?", a: "Môžu byť dostupné základné možnosti formátovania." },
  { q: "Ako sa líši od iných editorov?", a: "Zameriava sa na jednoduchosť, rýchlosť a písanie bez rušenia." },
];

const BG_FAQS: FaqItem[] = [
  { q: "Какво е Notepad Online?", a: "Notepad Online е браузърен текстов редактор за бързо писане, редактиране и запазване без инсталация." },
  { q: "Notepad Online безплатен ли е?", a: "Да, напълно безплатен и без скрити такси." },
  { q: "Трябва ли регистрация?", a: "Не, може да започнете веднага без акаунт." },
  { q: "Мога ли да запазвам бележките онлайн?", a: "Да, бележките могат да се запазват и отварят по-късно." },
  { q: "Има ли автоматично запазване?", a: "Да, съдържанието се запазва автоматично по време на писане." },
  { q: "Мога ли да достъпвам от различни устройства?", a: "Да, от мобилни устройства, таблет и компютър." },
  { q: "Сигурни ли са данните ми?", a: "Да, прилагат се мерки за защита на съдържанието и поверителност." },
  { q: "Мога ли да споделям бележки?", a: "Да, чрез линк за споделяне." },
  { q: "Работи ли на мобилни устройства?", a: "Да, интерфейсът е responsive и удобен за мобилни устройства." },
  { q: "Работи ли офлайн?", a: "Някои функции може да работят, но интернет е препоръчителен за запис и синхронизация." },
  { q: "По-добър ли е от Notepad/WordPad?", a: "Предлага модерни функции като достъп от много устройства и споделяне." },
  { q: "Какви функции включва?", a: "Изчистен редактор, auto-save, онлайн съхранение и лесно споделяне." },
  { q: "Мога ли да пиша документи?", a: "Да, подходящ е за бележки, чернови и прости документи." },
  { q: "Поддържа ли форматиране на текст?", a: "Може да има базови опции за форматиране." },
  { q: "С какво се различава от други редактори?", a: "Фокусира се върху простота, скорост и писане без разсейване." },
];

const HR_FAQS: FaqItem[] = [
  { q: "Što je Notepad Online?", a: "Notepad Online je tekstualni editor u pregledniku za brzo pisanje, uređivanje i spremanje bez instalacije." },
  { q: "Je li Notepad Online besplatan?", a: "Da, potpuno je besplatan bez skrivenih troškova." },
  { q: "Trebam li registraciju?", a: "Ne, možete početi odmah bez računa." },
  { q: "Mogu li spremati bilješke online?", a: "Da, bilješke se mogu spremiti i kasnije ponovno otvoriti." },
  { q: "Ima li automatsko spremanje?", a: "Da, sadržaj se automatski sprema tijekom tipkanja." },
  { q: "Mogu li pristupati s različitih uređaja?", a: "Da, s mobitela, tableta i računala." },
  { q: "Jesu li moji podaci sigurni?", a: "Da, primjenjuju se mjere privatnosti za zaštitu sadržaja." },
  { q: "Mogu li dijeliti bilješke?", a: "Da, putem poveznice za dijeljenje." },
  { q: "Radi li na mobitelu?", a: "Da, sučelje je mobilno prilagođeno." },
  { q: "Radi li offline?", a: "Neke funkcije mogu raditi, ali internet se preporučuje za spremanje i sinkronizaciju." },
  { q: "Je li bolji od Notepad/WordPad?", a: "Nudi moderne mogućnosti poput dijeljenja i pristupa s više uređaja." },
  { q: "Koje funkcije uključuje?", a: "Čist editor, auto-save, online pohrana i jednostavno dijeljenje." },
  { q: "Mogu li pisati dokumente?", a: "Da, pogodan je za bilješke, nacrte i jednostavne dokumente." },
  { q: "Podržava li formatiranje teksta?", a: "Mogu biti dostupne osnovne opcije formatiranja." },
  { q: "Po čemu se razlikuje od drugih editora?", a: "Fokus je na jednostavnosti, brzini i pisanju bez ometanja." },
];

const SR_FAQS: FaqItem[] = [
  { q: "Šta je Notepad Online?", a: "Notepad Online je tekst editor u pregledaču za brzo pisanje, uređivanje i čuvanje bez instalacije." },
  { q: "Da li je Notepad Online besplatan?", a: "Da, potpuno je besplatan i bez skrivenih troškova." },
  { q: "Da li je potrebna registracija?", a: "Ne, možete odmah da počnete bez naloga." },
  { q: "Mogu li da sačuvam beleške online?", a: "Da, beleške se mogu sačuvati i kasnije ponovo otvoriti." },
  { q: "Da li ima automatsko čuvanje?", a: "Da, sadržaj se automatski čuva tokom kucanja." },
  { q: "Mogu li da pristupim sa više uređaja?", a: "Da, sa mobilnog, tableta i računara." },
  { q: "Da li su moji podaci bezbedni?", a: "Da, primenjuju se mere privatnosti radi zaštite sadržaja." },
  { q: "Mogu li da podelim beleške?", a: "Da, preko linka za deljenje." },
  { q: "Da li radi na mobilnom?", a: "Da, interfejs je prilagođen mobilnim uređajima." },
  { q: "Da li radi offline?", a: "Neke funkcije mogu raditi, ali internet je preporučen za čuvanje i sinhronizaciju." },
  { q: "Da li je bolji od Notepad/WordPad?", a: "Nudi moderne funkcije kao što su deljenje i pristup sa više uređaja." },
  { q: "Koje funkcije uključuje?", a: "Čist editor, auto-save, online skladištenje i lako deljenje." },
  { q: "Mogu li da pišem dokumenta?", a: "Da, pogodan je za beleške, nacrte i jednostavna dokumenta." },
  { q: "Da li podržava formatiranje teksta?", a: "Mogu biti dostupne osnovne opcije formatiranja." },
  { q: "Po čemu se razlikuje od drugih editora?", a: "Fokusira se na jednostavnost, brzinu i pisanje bez ometanja." },
];

const UK_FAQS: FaqItem[] = [
  { q: "Що таке Notepad Online?", a: "Notepad Online — це текстовий редактор у браузері для швидкого написання, редагування та збереження нотаток без встановлення." },
  { q: "Notepad Online безкоштовний?", a: "Так, сервіс повністю безкоштовний і без прихованих платежів." },
  { q: "Потрібна реєстрація?", a: "Ні, можна почати одразу без акаунта." },
  { q: "Чи можна зберігати нотатки онлайн?", a: "Так, нотатки можна зберігати та відкривати пізніше." },
  { q: "Є автозбереження?", a: "Так, зміни зберігаються автоматично під час набору." },
  { q: "Чи доступно з різних пристроїв?", a: "Так, з телефону, планшета та комп’ютера." },
  { q: "Мої дані захищені?", a: "Так, використовуються заходи конфіденційності для захисту контенту." },
  { q: "Чи можна ділитися нотатками?", a: "Так, через посилання для поширення." },
  { q: "Працює на мобільних?", a: "Так, інтерфейс адаптований для мобільних пристроїв." },
  { q: "Працює офлайн?", a: "Деякі функції можуть працювати, але інтернет рекомендований для збереження та синхронізації." },
  { q: "Кращий за Notepad/WordPad?", a: "Має сучасні можливості: доступ із різних пристроїв та зручний обмін." },
  { q: "Які функції включає?", a: "Чистий редактор, автозбереження, онлайн-зберігання і швидке поширення." },
  { q: "Чи можна писати документи?", a: "Так, підходить для нотаток, чернеток і простих документів." },
  { q: "Підтримує форматування тексту?", a: "Можуть бути доступні базові опції форматування." },
  { q: "Чим відрізняється від інших редакторів?", a: "Фокус на простоті, швидкості та письмі без відволікань." },
];

const TA_FAQS: FaqItem[] = [
  { q: "Notepad Online என்பது என்ன?", a: "Notepad Online என்பது உலாவியில் இயங்கும் உரைத் திருத்தி. நிறுவல் இல்லாமல் உடனே குறிப்புகளை எழுத, திருத்த, சேமிக்கலாம்." },
  { q: "Notepad Online இலவசமா?", a: "ஆம், இது முழுமையாக இலவசம்; மறைமுக கட்டணங்கள் இல்லை." },
  { q: "பயன்படுத்த பதிவு தேவையா?", a: "இல்லை, கணக்கு இல்லாமல் உடனே பயன்படுத்தலாம்." },
  { q: "குறிப்புகளை ஆன்லைனில் சேமிக்கலாமா?", a: "ஆம், குறிப்புகளை சேமித்து பிறகு மீண்டும் திறந்து திருத்தலாம்." },
  { q: "Auto-save உண்டா?", a: "ஆம், தட்டச்சு செய்யும் போது தானாக சேமிக்கப்படும்." },
  { q: "வேறு சாதனங்களில் அணுகலாமா?", a: "ஆம், மொபைல், டேப்லெட், கணினி அனைத்திலும் அணுகலாம்." },
  { q: "என் தரவு பாதுகாப்பானதா?", a: "ஆம், உள்ளடக்கத்தை பாதுகாக்க தனியுரிமை நடவடிக்கைகள் பயன்படுத்தப்படுகின்றன." },
  { q: "குறிப்புகளை பகிர முடியுமா?", a: "ஆம், பகிர்வு இணைப்பின் மூலம் எளிதாக பகிரலாம்." },
  { q: "மொபைலில் வேலை செய்யுமா?", a: "ஆம், மொபைல் நட்பு வடிவமைப்புடன் நன்றாக இயங்கும்." },
  { q: "ஆஃப்லைனில் பயன்படுத்தலாமா?", a: "சில அம்சங்கள் இயங்கலாம், ஆனால் சேமிப்பு/ஒத்திசைவு కోసం இணையம் பரிந்துரைக்கப்படுகிறது." },
  { q: "Notepad/WordPad விட நல்லதா?", a: "பல சாதன அணுகல், பகிர்வு போன்ற நவீன அம்சங்கள் இதில் உள்ளன." },
  { q: "இதில் என்ன அம்சங்கள் உள்ளன?", a: "எளிய எடிட்டர், auto-save, ஆன்லைன் சேமிப்பு மற்றும் எளிய பகிர்வு." },
  { q: "டாக்குமெண்ட் எழுத பயன்படுத்தலாமா?", a: "ஆம், குறிப்புகள், வரைவு மற்றும் எளிய ஆவணங்களுக்கு பொருத்தமானது." },
  { q: "Text formatting ஆதரவு உள்ளதா?", a: "அடிப்படை வடிவமைப்பு விருப்பங்கள் இருக்கலாம்." },
  { q: "மற்ற எடிட்டர்களிலிருந்து வேறுபாடு என்ன?", a: "எளிமை, வேகம், கவனச்சிதறலில்லா எழுதுதல் ஆகியவற்றில் கவனம் செலுத்துகிறது." },
];

const TE_FAQS: FaqItem[] = [
  { q: "Notepad Online అంటే ఏమిటి?", a: "Notepad Online అనేది బ్రౌజర్‌లో పనిచేసే టెక్స్ట్ ఎడిటర్. ఇన్‌స్టాల్ చేయకుండా వెంటనే నోట్లు రాయడం, సవరించడం, సేవ్ చేయడం చేయవచ్చు." },
  { q: "Notepad Online ఉచితమా?", a: "అవును, ఇది పూర్తిగా ఉచితం మరియు ఎలాంటి గుప్త ఛార్జీలు లేవు." },
  { q: "వాడటానికి సైన్-అప్ అవసరమా?", a: "లేదు, ఖాతా లేకుండానే వెంటనే ఉపయోగించవచ్చు." },
  { q: "నోట్లు ఆన్‌లైన్‌లో సేవ్ చేయవచ్చా?", a: "అవును, సేవ్ చేసి తరువాత మళ్లీ తెరిచి సవరించవచ్చు." },
  { q: "Auto-save ఉందా?", a: "అవును, టైప్ చేస్తున్నప్పుడు ఆటోమేటిక్‌గా సేవ్ అవుతుంది." },
  { q: "వేర్వేరు పరికరాల్లో యాక్సెస్ చేయవచ్చా?", a: "అవును, మొబైల్, ట్యాబ్లెట్, డెస్క్‌టాప్‌లో అందుబాటులో ఉంటుంది." },
  { q: "నా డేటా సురక్షితమా?", a: "అవును, మీ కంటెంట్ రక్షణకు ప్రైవసీ చర్యలు అమలులో ఉన్నాయి." },
  { q: "నోట్లు షేర్ చేయవచ్చా?", a: "అవును, షేర్ లింక్ ద్వారా సులభంగా షేర్ చేయవచ్చు." },
  { q: "మొబైల్‌లో పనిచేస్తుందా?", a: "అవును, మొబైల్‌కు అనుకూలంగా బాగా పనిచేస్తుంది." },
  { q: "ఆఫ్లైన్‌లో పనిచేస్తుందా?", a: "కొన్ని ఫీచర్లు పనిచేయొచ్చు, కానీ సేవ్/సింక్ కోసం ఇంటర్నెట్ మంచిది." },
  { q: "Notepad/WordPad కంటే మెరుగైనదా?", a: "మల్టీ-డివైస్ యాక్సెస్, షేరింగ్ వంటి ఆధునిక సదుపాయాలు ఉన్నాయి." },
  { q: "ఏ ఫీచర్లు ఉన్నాయి?", a: "క్లీన్ ఎడిటర్, auto-save, ఆన్‌లైన్ స్టోరేజ్, సులభమైన షేరింగ్." },
  { q: "డాక్యుమెంట్లు రాయడానికి ఉపయోగించవచ్చా?", a: "అవును, నోట్లు, డ్రాఫ్టులు, సాధారణ డాక్యుమెంట్లకు అనుకూలం." },
  { q: "టెక్స్ట్ ఫార్మాటింగ్ సపోర్ట్ ఉందా?", a: "ప్రాథమిక ఫార్మాటింగ్ ఎంపికలు అందుబాటులో ఉండొచ్చు." },
  { q: "ఇతర ఎడిటర్లతో తేడా ఏమిటి?", a: "సరళత, వేగం, దృష్టి చెదరని రచన అనుభవంపై దృష్టి." },
];

const MR_FAQS: FaqItem[] = [
  { q: "Notepad Online म्हणजे काय?", a: "Notepad Online हे ब्राउझरमध्ये चालणारे टेक्स्ट एडिटर आहे. इंस्टॉल न करता पटकन नोट्स लिहा, संपादित करा आणि जतन करा." },
  { q: "Notepad Online मोफत आहे का?", a: "हो, पूर्णपणे मोफत आहे आणि कोणतेही लपलेले शुल्क नाही." },
  { q: "वापरण्यासाठी नोंदणी आवश्यक आहे का?", a: "नाही, खाते न बनवता लगेच वापर सुरू करू शकता." },
  { q: "मी नोट्स ऑनलाइन सेव्ह करू शकतो का?", a: "हो, नोट्स जतन करून नंतर पुन्हा संपादित करू शकता." },
  { q: "Auto-save आहे का?", a: "हो, टाइप करताना सामग्री आपोआप सेव्ह होते." },
  { q: "वेगवेगळ्या डिव्हाइसवरून वापरता येते का?", a: "हो, मोबाईल, टॅबलेट आणि डेस्कटॉपवर उपलब्ध आहे." },
  { q: "माझे डेटा सुरक्षित आहेत का?", a: "हो, सामग्री सुरक्षित ठेवण्यासाठी गोपनीयता उपाय लागू केलेले आहेत." },
  { q: "नोट्स शेअर करता येतात का?", a: "हो, शेअर लिंकद्वारे सहज शेअर करता येतात." },
  { q: "हे मोबाईलवर चालते का?", a: "हो, मोबाईलसाठी responsive आहे." },
  { q: "ऑफलाइन वापरता येते का?", a: "काही फीचर्स चालू शकतात, पण सेव्ह/सिंकसाठी इंटरनेट योग्य आहे." },
  { q: "Notepad/WordPad पेक्षा चांगले आहे का?", a: "यात मल्टी-डिव्हाइस ऍक्सेस आणि शेअरिंगसारखी आधुनिक फीचर्स आहेत." },
  { q: "मुख्य फीचर्स कोणती?", a: "क्लीन एडिटर, auto-save, ऑनलाइन स्टोरेज आणि सोपी शेअरिंग." },
  { q: "डॉक्युमेंट लिहिण्यासाठी वापरू शकतो का?", a: "हो, नोट्स, ड्राफ्ट आणि साध्या डॉक्युमेंटसाठी योग्य." },
  { q: "टेक्स्ट फॉरमॅटिंग सपोर्ट आहे का?", a: "मूलभूत फॉरमॅटिंग पर्याय उपलब्ध असू शकतात." },
  { q: "इतर एडिटर्सपेक्षा वेगळेपण काय?", a: "साधेपणा, वेग आणि विचलनमुक्त लेखन अनुभवावर भर." },
];

const GU_FAQS: FaqItem[] = [
  { q: "Notepad Online શું છે?", a: "Notepad Online એક બ્રાઉઝર આધારિત ટેક્સ્ટ એડિટર છે જેમાં તમે ઇન્સ્ટોલ કર્યા વગર તરત જ લખી, સંપાદિત કરી અને સાચવી શકો છો." },
  { q: "શું Notepad Online મફત છે?", a: "હા, સંપૂર્ણ મફત છે અને કોઈ છુપાયેલા ચાર્જ નથી." },
  { q: "વાપરવા માટે સાઇન-અપ જરૂરી છે?", a: "ના, ખાતું બનાવ્યા વગર તરત જ શરૂ કરી શકો છો." },
  { q: "શું હું નોંધો ઑનલાઇન સાચવી શકું?", a: "હા, નોંધોને સાચવીને પછી ફરીથી સંપાદિત કરી શકો છો." },
  { q: "Auto-save ઉપલબ્ધ છે?", a: "હા, ટાઇપ કરતી વખતે આપમેળે સાચવાય છે." },
  { q: "વિવિધ ડિવાઇસ પર ઍક્સેસ થઈ શકે?", a: "હા, મોબાઇલ, ટેબ્લેટ અને ડેસ્કટોપ પરથી." },
  { q: "મારો ડેટા સુરક્ષિત છે?", a: "હા, તમારી સામગ્રી સુરક્ષિત રાખવા ગોપનીયતા પગલાં છે." },
  { q: "શું હું નોંધો શેર કરી શકું?", a: "હા, શેર લિંકથી સરળતાથી શેર કરી શકો છો." },
  { q: "મોબાઇલ પર કામ કરે છે?", a: "હા, સંપૂર્ણ રીતે responsive છે." },
  { q: "ઓફલાઇન કામ કરે છે?", a: "કેટલાક ફીચર્સ ચાલી શકે, પરંતુ સાચવવા/સિંક માટે ઇન્ટરનેટ સારું છે." },
  { q: "Notepad/WordPad કરતા સારું છે?", a: "તેમાં મલ્ટી-ડિવાઇસ ઍક્સેસ અને શેરિંગ જેવી આધુનિક સુવિધાઓ છે." },
  { q: "મુખ્ય ફીચર્સ શું છે?", a: "ક્લીન એડિટર, auto-save, ઓનલાઇન સ્ટોરેજ અને સરળ શેરિંગ." },
  { q: "ડોક્યુમેન્ટ લખવા માટે વાપરી શકું?", a: "હા, નોંધો, ડ્રાફ્ટ અને સરળ દસ્તાવેજો માટે યોગ્ય છે." },
  { q: "ટેક્સ્ટ ફોર્મેટિંગ સપોર્ટ છે?", a: "મૂળભૂત ફોર્મેટિંગ વિકલ્પો ઉપલબ્ધ હોઈ શકે." },
  { q: "બીજા એડિટરથી શું અલગ?", a: "સરળતા, ઝડપ અને ધ્યાનભંગ વગર લખાણ પર ફોકસ." },
];

const KN_FAQS: FaqItem[] = [
  { q: "Notepad Online ಎಂದರೇನು?", a: "Notepad Online ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಕೆಲಸ ಮಾಡುವ ಪಠ್ಯ ಸಂಪಾದಕ. ಇನ್‌ಸ್ಟಾಲ್ ಇಲ್ಲದೇ ತಕ್ಷಣ ಟಿಪ್ಪಣಿಗಳನ್ನು ಬರೆಯಲು, ಸಂಪಾದಿಸಲು, ಉಳಿಸಲು ಸಾಧ್ಯ." },
  { q: "Notepad Online ಉಚಿತವೇ?", a: "ಹೌದು, ಸಂಪೂರ್ಣ ಉಚಿತ ಮತ್ತು ಯಾವುದೇ ಮರೆಮಾಚಿದ ಶುಲ್ಕಗಳಿಲ್ಲ." },
  { q: "ಬಳಸಲು ನೋಂದಣಿ ಬೇಕೆ?", a: "ಇಲ್ಲ, ಖಾತೆ ಇಲ್ಲದೇ ಕೂಡ ತಕ್ಷಣ ಬಳಸಬಹುದು." },
  { q: "ಟಿಪ್ಪಣಿಗಳನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಉಳಿಸಬಹುದೇ?", a: "ಹೌದು, ಉಳಿಸಿ ನಂತರ ಮತ್ತೆ ತೆರೆಯಬಹುದು." },
  { q: "Auto-save ಇದೆಯೇ?", a: "ಹೌದು, ಟೈಪ್ ಮಾಡುವಾಗ ಸ್ವಯಂ ಉಳಿಯುತ್ತದೆ." },
  { q: "ಬೇರೆ ಸಾಧನಗಳಲ್ಲಿ ಬಳಸಬಹುದೇ?", a: "ಹೌದು, ಮೊಬೈಲ್, ಟ್ಯಾಬ್ಲೆಟ್ ಮತ್ತು ಡೆಸ್ಕ್‌ಟಾಪ್‌ನಲ್ಲಿ." },
  { q: "ನನ್ನ ಡೇಟಾ ಸುರಕ್ಷಿತವೇ?", a: "ಹೌದು, ನಿಮ್ಮ ವಿಷಯವನ್ನು ರಕ್ಷಿಸಲು ಗೌಪ್ಯತಾ ಕ್ರಮಗಳಿವೆ." },
  { q: "ಟಿಪ್ಪಣಿಗಳನ್ನು ಹಂಚಬಹುದೇ?", a: "ಹೌದು, share link ಮೂಲಕ ಸುಲಭವಾಗಿ ಹಂಚಬಹುದು." },
  { q: "ಮೊಬೈಲ್‌ನಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆಯೇ?", a: "ಹೌದು, ಸಂಪೂರ್ಣ responsive ಆಗಿದೆ." },
  { q: "ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆಯೇ?", a: "ಕೆಲವು ವೈಶಿಷ್ಟ್ಯಗಳು ಕೆಲಸ ಮಾಡಬಹುದು, ಆದರೆ save/sync ಗೆ ಇಂಟರ್ನೆಟ್ ಉತ್ತಮ." },
  { q: "Notepad/WordPad ಗಿಂತ ಉತ್ತಮವೇ?", a: "multi-device access ಮತ್ತು sharing ನಂತಹ ಆಧುನಿಕ ವೈಶಿಷ್ಟ್ಯಗಳಿವೆ." },
  { q: "ಮುಖ್ಯ ವೈಶಿಷ್ಟ್ಯಗಳು ಯಾವುವು?", a: "clean editor, auto-save, online storage, easy sharing." },
  { q: "ಡಾಕ್ಯುಮೆಂಟ್ ಬರೆಯಲು ಬಳಸಬಹುದೇ?", a: "ಹೌದು, notes, drafts, simple documents ಗೆ ಸೂಕ್ತ." },
  { q: "text formatting ಬೆಂಬಲ ಇದೆಯೇ?", a: "ಮೂಲಭೂತ formatting ಆಯ್ಕೆಗಳು ಲಭ್ಯವಾಗಬಹುದು." },
  { q: "ಇತರೆ editor ಗಳಿಗಿಂತ ವ್ಯತ್ಯಾಸ ಏನು?", a: "ಸರಳತೆ, ವೇಗ ಮತ್ತು distraction-free writing ಮೇಲೆ ಒತ್ತು." },
];

const ML_FAQS: FaqItem[] = [
  { q: "Notepad Online എന്താണ്?", a: "Notepad Online ബ്രൗസറിൽ പ്രവർത്തിക്കുന്ന ടെക്സ്റ്റ് എഡിറ്ററാണ്. ഇൻസ്റ്റാൾ ചെയ്യാതെ തന്നെ കുറിപ്പുകൾ എഴുതാനും തിരുത്താനും സേവ് ചെയ്യാനും കഴിയും." },
  { q: "Notepad Online സൗജന്യമാണോ?", a: "അതെ, ഇത് പൂർണ്ണമായും സൗജന്യമാണ്; ഒളിഞ്ഞ ചെലവുകളൊന്നുമില്ല." },
  { q: "ഉപയോഗിക്കാൻ രജിസ്ട്രേഷൻ വേണോ?", a: "ഇല്ല, അക്കൗണ്ട് ഇല്ലാതെയും ഉടൻ ഉപയോഗിക്കാം." },
  { q: "കുറിപ്പുകൾ ഓൺലൈനിൽ സേവ് ചെയ്യാമോ?", a: "അതെ, കുറിപ്പുകൾ സേവ് ചെയ്ത് പിന്നീട് വീണ്ടും തിരുത്താം." },
  { q: "Auto-save ഉണ്ടോ?", a: "അതെ, ടൈപ്പ് ചെയ്യുമ്പോൾ സ്വയം സേവ് ചെയ്യും." },
  { q: "വ്യത്യസ്ത ഉപകരണങ്ങളിൽ നിന്ന് ആക്‌സസ് സാധ്യമാണോ?", a: "അതെ, മൊബൈൽ, ടാബ്ലറ്റ്, ഡെസ്ക്ടോപ്പ് എന്നിവയിൽ ലഭ്യമാണ്." },
  { q: "എന്റെ ഡാറ്റ സുരക്ഷിതമാണോ?", a: "അതെ, ഉള്ളടക്കം സംരക്ഷിക്കാൻ സ്വകാര്യതാ നടപടികൾ ഉണ്ട്." },
  { q: "കുറിപ്പുകൾ ഷെയർ ചെയ്യാമോ?", a: "അതെ, ഷെയർ ലിങ്ക് വഴി എളുപ്പത്തിൽ പങ്കിടാം." },
  { q: "മൊബൈലിൽ പ്രവർത്തിക്കുമോ?", a: "അതെ, മൊബൈൽ-ഫ്രണ്ട്ലിയും responsive-ഉം ആണ്." },
  { q: "ഓഫ്‌ലൈൻ ഉപയോഗിക്കാമോ?", a: "ചില ഫീച്ചറുകൾ പ്രവർത്തിച്ചേക്കാം, പക്ഷേ save/sync ന് ഇന്റർനെറ്റ് നല്ലത്." },
  { q: "Notepad/WordPad-നേക്കാൾ നല്ലതാണോ?", a: "multi-device access, sharing പോലുള്ള ആധുനിക സൗകര്യങ്ങൾ നൽകുന്നു." },
  { q: "പ്രധാന ഫീച്ചറുകൾ എന്തൊക്കെയാണ്?", a: "clean editor, auto-save, online storage, easy sharing." },
  { q: "ഡോക്യുമെന്റുകൾ എഴുതാൻ പറ്റുമോ?", a: "അതെ, കുറിപ്പുകൾ, ഡ്രാഫ്റ്റുകൾ, ലളിതമായ ഡോക്യുമെന്റുകൾക്ക് അനുയോജ്യം." },
  { q: "text formatting പിന്തുണയുണ്ടോ?", a: "അടിസ്ഥാന formatting ഓപ്ഷനുകൾ ലഭ്യമായേക്കാം." },
  { q: "മറ്റു എഡിറ്ററുകളിൽ നിന്ന് എന്താണ് വ്യത്യാസം?", a: "ലളിതത്വം, വേഗം, distraction-free എഴുത്ത് അനുഭവം." },
];

const SI_FAQS: FaqItem[] = [
  { q: "Notepad Online කියන්නේ මොකක්ද?", a: "Notepad Online කියන්නේ browser එක තුළ ක්‍රියා කරන text editor එකක්. install නොකරම notes ලියන්න, edit කරන්න, save කරන්න පුළුවන්." },
  { q: "Notepad Online නොමිලේද?", a: "ඔව්, සම්පූර්ණයෙන්ම නොමිලේ සහ සැඟවුණු ගාස්තු නැහැ." },
  { q: "භාවිතයට account එකක් ඕනෙද?", a: "නැහැ, account එකක් නැතිවත් වහාම භාවිතා කළ හැක." },
  { q: "notes online save කරන්න පුළුවන්ද?", a: "ඔව්, save කරලා පසුව නැවත edit කළ හැක." },
  { q: "Auto-save තියෙනවද?", a: "ඔව්, ටයිප් කරන අතරතුර auto-save වේ." },
  { q: "වෙනත් devices වලින් access කරන්න පුළුවන්ද?", a: "ඔව්, mobile, tablet, desktop වලින් භාවිතා කළ හැක." },
  { q: "මගේ data safe ද?", a: "ඔව්, ඔබේ content ආරක්ෂා කිරීමට privacy ක්‍රියාමාර්ග ඇත." },
  { q: "notes share කරන්න පුළුවන්ද?", a: "ඔව්, share link එකකින් පහසුවෙන් share කළ හැක." },
  { q: "mobile වල වැඩ කරයිද?", a: "ඔව්, responsive design එක නිසා mobile වල හොඳින් වැඩ කරයි." },
  { q: "offline භාවිතා කරන්න පුළුවන්ද?", a: "කිසියම් basic features වැඩ කරන්න පුළුවන්, නමුත් save/sync සඳහා internet හොඳයි." },
  { q: "Notepad/WordPad වලට වඩා හොඳද?", a: "multi-device access සහ sharing වැනි modern features ලබාදේ." },
  { q: "මූලික features මොනවද?", a: "clean editor, auto-save, online storage සහ easy sharing." },
  { q: "documents ලියන්න පුළුවන්ද?", a: "ඔව්, notes, drafts, simple documents සඳහා සුදුසුය." },
  { q: "text formatting support තියෙනවද?", a: "basic formatting options තිබිය හැක." },
  { q: "අනිත් editors වලට වඩා වෙනස මොකක්ද?", a: "සරලත්වය, වේගය සහ distraction-free writing experience එකට focus කරයි." },
];

const NE_FAQS: FaqItem[] = [
  { q: "Notepad Online के हो?", a: "Notepad Online ब्राउजरमा चल्ने टेक्स्ट एडिटर हो, जसले बिना इन्स्टल तुरुन्त नोट लेख्न, सम्पादन गर्न र सुरक्षित गर्न दिन्छ।" },
  { q: "Notepad Online निःशुल्क हो?", a: "हो, यो पूर्ण रूपमा निःशुल्क हो र लुकेका शुल्क छैनन्।" },
  { q: "चलाउन साइन-अप चाहिन्छ?", a: "चाहिँदैन, खाताबिना नै तुरुन्त सुरु गर्न सकिन्छ।" },
  { q: "नोटहरू अनलाइन सुरक्षित गर्न मिल्छ?", a: "मिल्छ, नोटहरू सुरक्षित गरेर पछि फेरि सम्पादन गर्न सकिन्छ।" },
  { q: "Auto-save छ?", a: "छ, टाइप गर्दा सामग्री स्वतः सुरक्षित हुन्छ।" },
  { q: "फरक-फरक डिभाइसबाट पहुँच हुन्छ?", a: "हुन्छ, मोबाइल, ट्याब्लेट र कम्प्युटर सबैबाट पहुँच गर्न सकिन्छ।" },
  { q: "मेरो डाटा सुरक्षित छ?", a: "छ, सामग्री सुरक्षित राख्न गोपनीयता उपायहरू लागू छन्।" },
  { q: "नोटहरू सेयर गर्न मिल्छ?", a: "मिल्छ, सेयर लिंकबाट सजिलै पठाउन सकिन्छ।" },
  { q: "मोबाइलमा काम गर्छ?", a: "गर्छ, मोबाइलमैत्री responsive इन्टरफेस छ।" },
  { q: "अफलाइन प्रयोग गर्न मिल्छ?", a: "केही फिचर चल्न सक्छन्, तर save/sync का लागि इन्टरनेट राम्रो हुन्छ।" },
  { q: "Notepad/WordPad भन्दा राम्रो हो?", a: "यसमा multi-device access र sharing जस्ता आधुनिक सुविधा छन्।" },
  { q: "मुख्य फिचरहरू के छन्?", a: "clean editor, auto-save, online storage र easy sharing." },
  { q: "डोकुमेन्ट लेख्न प्रयोग गर्न मिल्छ?", a: "मिल्छ, नोट, ड्राफ्ट र सामान्य डोकुमेन्टका लागि उपयुक्त छ।" },
  { q: "text formatting सपोर्ट छ?", a: "basic formatting विकल्प उपलब्ध हुन सक्छन्।" },
  { q: "अन्य editor भन्दा फरक के हो?", a: "सरलता, गति र distraction-free लेखन अनुभवमा फोकस गर्छ।" },
];

const MS_FAQS: FaqItem[] = [
  { q: "Apakah Notepad Online?", a: "Notepad Online ialah editor teks berasaskan pelayar untuk menulis, mengedit, dan menyimpan nota tanpa pemasangan." },
  { q: "Adakah Notepad Online percuma?", a: "Ya, sepenuhnya percuma tanpa caj tersembunyi." },
  { q: "Perlukah saya daftar akaun?", a: "Tidak, anda boleh mula serta-merta tanpa log masuk." },
  { q: "Boleh simpan nota secara online?", a: "Ya, nota boleh disimpan dan dibuka semula bila-bila masa." },
  { q: "Ada auto-save?", a: "Ya, kandungan disimpan automatik semasa menaip." },
  { q: "Boleh akses dari peranti berbeza?", a: "Ya, dari telefon, tablet, dan desktop." },
  { q: "Adakah data saya selamat?", a: "Ya, langkah privasi digunakan untuk melindungi kandungan anda." },
  { q: "Boleh kongsi nota?", a: "Ya, kongsi melalui pautan dengan mudah." },
  { q: "Berfungsi pada mudah alih?", a: "Ya, antaramuka responsif dan mesra mudah alih." },
  { q: "Boleh guna offline?", a: "Sebahagian ciri mungkin berfungsi, tetapi internet disyorkan untuk simpan dan sync." },
  { q: "Lebih baik daripada Notepad/WordPad?", a: "Ia menawarkan ciri moden seperti akses merentas peranti dan perkongsian." },
  { q: "Ciri utama apa?", a: "Editor ringkas, auto-save, storan online, dan perkongsian mudah." },
  { q: "Boleh tulis dokumen?", a: "Ya, sesuai untuk nota, draf, dan dokumen ringkas." },
  { q: "Sokong format teks?", a: "Pilihan pemformatan asas mungkin tersedia." },
  { q: "Apa beza dengan editor lain?", a: "Fokus pada kesederhanaan, kelajuan, dan penulisan tanpa gangguan." },
];

const SW_FAQS: FaqItem[] = [
  { q: "Notepad Online ni nini?", a: "Notepad Online ni kihariri cha maandishi kwenye kivinjari cha kuandika, kuhariri, na kuhifadhi noti bila kusakinisha." },
  { q: "Je, Notepad Online ni bure?", a: "Ndiyo, ni bure kabisa bila gharama fiche." },
  { q: "Nahitaji kujisajili?", a: "Hapana, unaweza kuanza mara moja bila akaunti." },
  { q: "Naweza kuhifadhi noti mtandaoni?", a: "Ndiyo, noti zinaweza kuhifadhiwa na kufunguliwa tena baadaye." },
  { q: "Ina auto-save?", a: "Ndiyo, huhifadhi kiotomatiki unapochapa." },
  { q: "Naweza kufikia kutoka vifaa tofauti?", a: "Ndiyo, kutoka simu, tablet, na kompyuta." },
  { q: "Data yangu iko salama?", a: "Ndiyo, hatua za faragha zinalinda maudhui yako." },
  { q: "Naweza kushiriki noti?", a: "Ndiyo, kwa kiungo cha kushiriki." },
  { q: "Inafanya kazi kwenye simu?", a: "Ndiyo, ni responsive na rafiki kwa simu." },
  { q: "Inaweza kufanya kazi offline?", a: "Baadhi ya vipengele vinaweza kufanya kazi, lakini intaneti inapendekezwa kwa kuhifadhi na kusawazisha." },
  { q: "Ni bora kuliko Notepad/WordPad?", a: "Inatoa vipengele vya kisasa kama ufikiaji wa vifaa vingi na kushiriki." },
  { q: "Vipengele vikuu ni vipi?", a: "Kihariri safi, auto-save, hifadhi mtandaoni, na kushiriki kwa urahisi." },
  { q: "Naweza kuandika nyaraka?", a: "Ndiyo, inafaa kwa noti, drafti, na nyaraka rahisi." },
  { q: "Inaunga mkono formatting?", a: "Chaguo za msingi za formatting zinaweza kupatikana." },
  { q: "Tofauti yake na vihariri vingine ni ipi?", a: "Inalenga urahisi, kasi, na kuandika bila bughudha." },
];

const AF_FAQS: FaqItem[] = [
  { q: "Wat is Notepad Online?", a: "Notepad Online is ’n blaaier-gebaseerde teksredigeerder om notas te skryf, te wysig en te stoor sonder installasie." },
  { q: "Is Notepad Online gratis?", a: "Ja, heeltemal gratis en sonder versteekte koste." },
  { q: "Moet ek registreer?", a: "Nee, jy kan dadelik begin sonder ’n rekening." },
  { q: "Kan ek notas aanlyn stoor?", a: "Ja, notas kan gestoor en later weer oopgemaak word." },
  { q: "Het dit outomatiese stoor?", a: "Ja, inhoud word outomaties gestoor terwyl jy tik." },
  { q: "Kan ek dit op verskillende toestelle gebruik?", a: "Ja, op selfoon, tablet en rekenaar." },
  { q: "Is my data veilig?", a: "Ja, privaatheidsmaatreëls beskerm jou inhoud." },
  { q: "Kan ek notas deel?", a: "Ja, via ’n deelbare skakel." },
  { q: "Werk dit op selfoon?", a: "Ja, dit is mobiel-vriendelik en responsief." },
  { q: "Werk dit vanlyn?", a: "Sommige funksies kan werk, maar internet word aanbeveel vir stoor en sinkronisering." },
  { q: "Is dit beter as Notepad/WordPad?", a: "Dit bied moderne funksies soos multi-toestel toegang en deel." },
  { q: "Watter kernfunksies het dit?", a: "Skoon redigeerder, outomatiese stoor, aanlyn stoor, en maklike deel." },
  { q: "Kan ek dokumente daarmee skryf?", a: "Ja, ideaal vir notas, konsepte en eenvoudige dokumente." },
  { q: "Ondersteun dit teksformatering?", a: "Basiese formateringsopsies kan beskikbaar wees." },
  { q: "Hoe verskil dit van ander redigeerders?", a: "Fokus op eenvoud, spoed en afleidingsvrye skryf." },
];

const AM_FAQS: FaqItem[] = [
  { q: "Notepad Online ምንድነው?", a: "Notepad Online በብራውዘር የሚሰራ የጽሑፍ አርታዒ ሲሆን ያለ መጫን መጻፍ፣ ማርትዕ እና ማስቀመጥ ይችላሉ።" },
  { q: "Notepad Online ነፃ ነው?", a: "አዎ፣ ሙሉ በሙሉ ነፃ ነው እና ድብቅ ክፍያ የለም።" },
  { q: "ለመጠቀም መመዝገብ ያስፈልጋል?", a: "አይ፣ መለያ ሳይፈጥሩ ወዲያውኑ መጠቀም ይችላሉ።" },
  { q: "ማስታወሻ መስመር ላይ ማስቀመጥ እችላለሁ?", a: "አዎ፣ ማስቀመጥ እና በኋላ እንደገና መክፈት ይችላሉ።" },
  { q: "Auto-save አለ?", a: "አዎ፣ ሲተይፉ በራስ-ሰር ይቀመጣል።" },
  { q: "በተለያዩ መሳሪያዎች ላይ መጠቀም እችላለሁ?", a: "አዎ፣ በስልክ፣ በታብሌት እና በኮምፒዩተር ላይ ይሰራል።" },
  { q: "ውሂቤ ደህንነቱ የተጠበቀ ነው?", a: "አዎ፣ ይዘት ለመጠበቅ የግላዊነት መደበኛ እርምጃዎች አሉ።" },
  { q: "ማስታወሻ ማጋራት እችላለሁ?", a: "አዎ፣ በማጋራት አገናኝ ቀላል ነው።" },
  { q: "በሞባይል ይሰራል?", a: "አዎ፣ ለሞባይል ተስማሚ እና responsive ነው።" },
  { q: "ከመስመር ውጭ ይሰራል?", a: "አንዳንድ ባህሪያት ሊሰሩ ይችላሉ፣ ግን ለማስቀመጥ እና ለማመሳሰል ኢንተርኔት ይመከራል።" },
  { q: "ከNotepad/WordPad ይሻላል?", a: "እንደ ብዙ መሳሪያ መዳረሻ እና ማጋራት ያሉ ዘመናዊ ባህሪያት ያቀርባል።" },
  { q: "ዋና ባህሪያት ምንድን ናቸው?", a: "ንጹህ አርታዒ፣ auto-save፣ መስመር ላይ ማከማቻ እና ቀላል ማጋራት።" },
  { q: "ሰነድ ለመጻፍ ይጠቅማል?", a: "አዎ፣ ለማስታወሻ፣ ረቂቅ እና ቀላል ሰነዶች ተስማሚ ነው።" },
  { q: "text formatting ይደግፋል?", a: "መሠረታዊ የቅርጸ-ጽሑፍ አማራጮች ሊኖሩ ይችላሉ።" },
  { q: "ከሌሎች አርታዒዎች የሚለየው ምንድነው?", a: "ቀላልነት፣ ፍጥነት እና ያለ ማስታወቂያ መጻፍ ላይ ያተኩራል።" },
];

const SO_FAQS: FaqItem[] = [
  { q: "Waa maxay Notepad Online?", a: "Notepad Online waa tifaftire qoraal oo browser-ka ku shaqeeya, si aad u qorto, u saxdo, uguna kaydiso qoraallo adigoon wax rakibin." },
  { q: "Notepad Online ma bilaash baa?", a: "Haa, waa gebi ahaan bilaash oo aan lahayn kharash qarsoon." },
  { q: "Ma u baahanahay koonto?", a: "Maya, waxaad isla markiiba bilaabi kartaa adigoon isdiiwaangelin." },
  { q: "Ma kaydin karaa qoraalladayda online?", a: "Haa, qoraallada waa la kaydin karaa oo mar dambe dib baa loo furi karaa." },
  { q: "Auto-save ma leeyahay?", a: "Haa, waxa uu si toos ah u kaydiyaa intaad qorayso." },
  { q: "Ma ka gali karaa qalabyo kala duwan?", a: "Haa, mobil, tablet, iyo desktop." },
  { q: "Xogtaydu ma ammaan baa?", a: "Haa, waxaa jira tallaabooyin asturnaanta ah oo ilaalinaya xogtaada." },
  { q: "Ma wadaagi karaa qoraallada?", a: "Haa, waxaad ku wadaagi kartaa link si fudud." },
  { q: "Miyaa mobilka ka shaqeeyaa?", a: "Haa, waa responsive oo mobil-friendly ah." },
  { q: "Offline ma shaqeeyaa?", a: "Qaar ka mid ah astaamaha way shaqayn karaan, laakiin internet ayaa fiican kaydin iyo sync." },
  { q: "Ma ka fiican yahay Notepad/WordPad?", a: "Wuxuu bixiyaa astaamo casri ah sida multi-device access iyo wadaagis." },
  { q: "Astaamaha ugu muhiimsan waa maxay?", a: "Editor nadiif ah, auto-save, online storage, iyo wadaagis fudud." },
  { q: "Ma ku qori karaa dukumiintiyo?", a: "Haa, wuxuu ku habboon yahay notes, drafts, iyo dukumiintiyo fudud." },
  { q: "Ma taageeraa text formatting?", a: "Xulashooyin formatting aasaasi ah ayaa jiri kara." },
  { q: "Maxaa kaga duwan editor-rada kale?", a: "Wuxuu diiradda saaraa fudeyd, xawaare, iyo qorid aan mashquul lahayn." },
];

const YO_FAQS: FaqItem[] = [
  { q: "Kí ni Notepad Online?", a: "Notepad Online jẹ olootu ọrọ lori aṣàwákiri fun kikọ, ṣiṣatunkọ ati fífi akọsilẹ pamọ lai fi sọfitiwia sori ẹrọ." },
  { q: "Ṣe Notepad Online jẹ ọfẹ?", a: "Bẹ́ẹ̀ni, o jẹ ọfẹ patapata lai si owo pamọ." },
  { q: "Ṣe mo nilo ìforúkọsílẹ?", a: "Rárá, o le bẹrẹ lẹsẹkẹsẹ lai ṣẹda akọọlẹ." },
  { q: "Ṣe mo le fipamọ akọsilẹ mi lori ayelujara?", a: "Bẹ́ẹ̀ni, o le fipamọ wọn ki o ṣi i lẹ́yìnna." },
  { q: "Ṣe auto-save wa?", a: "Bẹ́ẹ̀ni, a n fipamọ laifọwọyi nigba ti o n kọ." },
  { q: "Ṣe mo le wọle lati ẹrọ oriṣiriṣi?", a: "Bẹ́ẹ̀ni, lori foonu, tabulẹti ati kọmputa." },
  { q: "Ṣe data mi wa ni aabo?", a: "Bẹ́ẹ̀ni, a lo ilana ìpamọ lati daabobo akoonu rẹ." },
  { q: "Ṣe mo le pin akọsilẹ?", a: "Bẹ́ẹ̀ni, pẹlu ọna asopọ pinpin." },
  { q: "Ṣe o n ṣiṣẹ lori alagbeka?", a: "Bẹ́ẹ̀ni, oju-iwe rẹ jẹ responsive fun alagbeka." },
  { q: "Ṣe o le ṣiṣẹ offline?", a: "Diẹ ninu awọn ẹya le ṣiṣẹ, ṣugbọn intanẹẹti ni a ṣeduro fun fipamọ ati sisopọ." },
  { q: "Ṣe o dara ju Notepad/WordPad lọ?", a: "O ni awọn ẹya igbalode bii iraye lori ọpọlọpọ ẹrọ ati pinpin." },
  { q: "Awọn ẹya pataki wo ni o wa?", a: "Editor to mọ, auto-save, online storage ati pinpin rọọrun." },
  { q: "Ṣe mo le lo fun kikọ awọn iwe?", a: "Bẹ́ẹ̀ni, o dara fun akọsilẹ, àkọsílẹ ìbẹrẹ ati iwe ti o rọrun." },
  { q: "Ṣe o ṣe atilẹyin formatting ọrọ?", a: "Awọn aṣayan formatting ipilẹ le wa." },
  { q: "Kini o yato si awọn olootu miiran?", a: "O dojukọ irọrun, iyara ati kikọ lai idamu." },
];

const IG_FAQS: FaqItem[] = [
  { q: "Gịnị bụ Notepad Online?", a: "Notepad Online bụ text editor na-arụ ọrụ na browser maka ide, idezi na ichekwa ederede n’enweghị nrụnye." },
  { q: "Notepad Online bụ n’efu?", a: "Ee, ọ bụ n’efu kpamkpam, enweghị ụgwọ zoro ezo." },
  { q: "A ga m ede aha tupu m jiri ya?", a: "Mba, ị nwere ike ịmalite ozugbo na-enweghị akaụntụ." },
  { q: "Enwere m ike ichekwa ndetu n’ịntanet?", a: "Ee, ị nwere ike ichekwa ndetu ma mepee ya ọzọ n’ọdịnihu." },
  { q: "Ọ nwere auto-save?", a: "Ee, a na-echekwa ihe ị na-ede na-akpaghị aka." },
  { q: "Enwere m ike iji ya na ngwaọrụ dị iche iche?", a: "Ee, na ekwentị, tablet na kọmputa." },
  { q: "Data m dị nchebe?", a: "Ee, e nwere usoro nzuzo iji chebe ọdịnaya gị." },
  { q: "Enwere m ike ikekọrịta ndetu?", a: "Ee, site na link ịkekọrịta." },
  { q: "Ọ na-arụ ọrụ na mobile?", a: "Ee, interface ya bụ mobile-friendly." },
  { q: "Ọ na-arụ ọrụ offline?", a: "Ụfọdụ atụmatụ nwere ike ịrụ ọrụ, mana ịntanet dị mma maka nchekwa na sync." },
  { q: "Ọ ka mma karịa Notepad/WordPad?", a: "Ọ na-enye atụmatụ oge a dịka multi-device access na sharing." },
  { q: "Kedu atụmatụ bụ isi?", a: "Editor dị ọcha, auto-save, online storage na sharing dị mfe." },
  { q: "Enwere m ike ide akwụkwọ n’ime ya?", a: "Ee, ọ dabara maka ndetu, draft na akwụkwọ dị mfe." },
  { q: "Ọ na-akwado text formatting?", a: "Ụfọdụ nhọrọ formatting isi nwere ike ịdị." },
  { q: "Kedu ka o si dị iche na editor ndị ọzọ?", a: "Ọ na-elekwasị anya na mfe, ọsọ na ide na-enweghị mgbagwoju anya." },
];

const HA_FAQS: FaqItem[] = [
  { q: "Menene Notepad Online?", a: "Notepad Online editan rubutu ne na browser don rubutu, gyara da ajiye bayanai ba tare da girkawa ba." },
  { q: "Notepad Online kyauta ne?", a: "Eh, kyauta ne gaba ɗaya ba tare da ɓoyayyun kuɗi ba." },
  { q: "Sai na yi rajista?", a: "A’a, zaka iya fara amfani nan take ba tare da asusu ba." },
  { q: "Zan iya ajiye bayanaina online?", a: "Eh, za a iya ajiye bayanai kuma a bude su daga baya." },
  { q: "Akwai auto-save?", a: "Eh, yana ajiye abin da kake rubutawa kai tsaye." },
  { q: "Zan iya amfani da shi a na'urori daban-daban?", a: "Eh, a waya, tablet da kwamfuta." },
  { q: "Bayanan nawa suna da tsaro?", a: "Eh, ana amfani da matakan sirri don kare bayananka." },
  { q: "Zan iya raba bayanai?", a: "Eh, ta hanyar link na raba." },
  { q: "Yana aiki a wayar hannu?", a: "Eh, yana da responsive kuma mobile-friendly." },
  { q: "Yana aiki offline?", a: "Wasu siffofi na iya aiki, amma internet yana da kyau don ajiya da sync." },
  { q: "Ya fi Notepad/WordPad?", a: "Yana da siffofi na zamani kamar amfani a na'urori da dama da raba bayanai." },
  { q: "Wadanne manyan siffofi yake da su?", a: "Editor mai tsabta, auto-save, online storage da saukin rabawa." },
  { q: "Zan iya rubuta documents?", a: "Eh, ya dace da notes, drafts da sauƙaƙan documents." },
  { q: "Yana goyon bayan formatting?", a: "Za a iya samun basic formatting options." },
  { q: "Me ya bambanta shi da sauran editors?", a: "Yana mai da hankali ga sauƙi, sauri da rubutu ba tare da damuwa ba." },
];

const UZ_FAQS: FaqItem[] = [
  { q: "Notepad Online nima?", a: "Notepad Online bu brauzerda ishlaydigan matn muharriri bo‘lib, o‘rnatmasdan yozish, tahrirlash va saqlash imkonini beradi." },
  { q: "Notepad Online bepulmi?", a: "Ha, u to‘liq bepul va yashirin to‘lovlarsiz." },
  { q: "Foydalanish uchun ro‘yxatdan o‘tish kerakmi?", a: "Yo‘q, hisob ochmasdan darhol boshlashingiz mumkin." },
  { q: "Eslatmalarni onlayn saqlash mumkinmi?", a: "Ha, eslatmalarni saqlab, keyin qayta ochish mumkin." },
  { q: "Auto-save bormi?", a: "Ha, yozayotganingizda avtomatik saqlanadi." },
  { q: "Turli qurilmalardan kirsa bo‘ladimi?", a: "Ha, telefon, planshet va kompyuterdan." },
  { q: "Ma’lumotlarim xavfsizmi?", a: "Ha, kontentni himoya qilish uchun maxfiylik choralar qo‘llanadi." },
  { q: "Eslatmalarni ulashish mumkinmi?", a: "Ha, ulashish havolasi orqali oson." },
  { q: "Mobil qurilmada ishlaydimi?", a: "Ha, mobilga mos va responsive." },
  { q: "Offline ishlaydimi?", a: "Ba’zi funksiyalar ishlashi mumkin, ammo saqlash va sinxronlash uchun internet tavsiya etiladi." },
  { q: "Notepad/WordPad dan yaxshiroqmi?", a: "U ko‘p qurilmada kirish va ulashish kabi zamonaviy imkoniyatlarni beradi." },
  { q: "Asosiy funksiyalari nimalar?", a: "Toza editor, auto-save, online storage va oson ulashish." },
  { q: "Hujjat yozish uchun mosmi?", a: "Ha, eslatma, draft va oddiy hujjatlar uchun qulay." },
  { q: "Matn formatlashni qo‘llab-quvvatlaydimi?", a: "Asosiy formatlash variantlari mavjud bo‘lishi mumkin." },
  { q: "Boshqa editorlardan nimasi bilan farq qiladi?", a: "Soddalik, tezlik va chalg‘itmaydigan yozishga urg‘u beradi." },
];

const KK_FAQS: FaqItem[] = [
  { q: "Notepad Online деген не?", a: "Notepad Online — браузерде жұмыс істейтін мәтіндік редактор. Орнатусыз жазуға, өңдеуге және сақтауға болады." },
  { q: "Notepad Online тегін бе?", a: "Иә, толық тегін және жасырын төлемдер жоқ." },
  { q: "Пайдалану үшін тіркелу керек пе?", a: "Жоқ, аккаунтсыз бірден бастай аласыз." },
  { q: "Жазбаларды онлайн сақтауға бола ма?", a: "Иә, жазбаларды сақтап, кейін қайта ашуға болады." },
  { q: "Auto-save бар ма?", a: "Иә, теріп жатқанда автоматты түрде сақталады." },
  { q: "Әртүрлі құрылғылардан кіруге бола ма?", a: "Иә, телефон, планшет және компьютерден." },
  { q: "Деректерім қауіпсіз бе?", a: "Иә, мазмұнды қорғау үшін құпиялылық шаралары қолданылады." },
  { q: "Жазбаларды бөлісуге бола ма?", a: "Иә, бөлісу сілтемесі арқылы оңай." },
  { q: "Мобильді құрылғыда жұмыс істей ме?", a: "Иә, мобильге бейімделген және responsive." },
  { q: "Офлайн жұмыс істей ме?", a: "Кейбір мүмкіндіктер жұмыс істеуі мүмкін, бірақ сақтау мен синхрондау үшін интернет ұсынылады." },
  { q: "Notepad/WordPad-тен жақсы ма?", a: "Көп құрылғыдан қолжетімділік және бөлісу сияқты заманауи мүмкіндіктер бар." },
  { q: "Негізгі мүмкіндіктері қандай?", a: "Таза редактор, auto-save, online сақтау және оңай бөлісу." },
  { q: "Құжат жазуға бола ма?", a: "Иә, жазба, драфт және қарапайым құжаттарға ыңғайлы." },
  { q: "Мәтін форматтауды қолдай ма?", a: "Негізгі форматтау опциялары болуы мүмкін." },
  { q: "Басқа редакторлардан айырмашылығы неде?", a: "Қарапайымдық, жылдамдық және алаңдатусыз жазуға назар аударады." },
];

const KY_FAQS: FaqItem[] = [
  { q: "Notepad Online деген эмне?", a: "Notepad Online — браузерде иштеген текст редактору. Орнотпой эле жазып, түзөтүп жана сактай аласыз." },
  { q: "Notepad Online бекерби?", a: "Ооба, толугу менен бекер жана жашыруун төлөмдөр жок." },
  { q: "Колдонуу үчүн катталуу керекпи?", a: "Жок, аккаунтсуз эле дароо баштасаңыз болот." },
  { q: "Жазууларды онлайн сактоого болобу?", a: "Ооба, сактап, кийин кайра ача аласыз." },
  { q: "Auto-save барбы?", a: "Ооба, терип жатканда автоматтык сакталат." },
  { q: "Ар башка түзмөктөн кирсе болобу?", a: "Ооба, телефон, планшет жана компьютерден." },
  { q: "Маалыматтарым коопсузбу?", a: "Ооба, мазмунду коргоо үчүн купуялык чаралары колдонулат." },
  { q: "Жазууларды бөлүшө аламбы?", a: "Ооба, бөлүшүү шилтемеси аркылуу оңой." },
  { q: "Мобилде иштейби?", a: "Ооба, мобилге ылайыкташкан responsive интерфейс." },
  { q: "Офлайн иштейби?", a: "Айрым функциялар иштеши мүмкүн, бирок сактоо жана синхрон үчүн интернет жакшы." },
  { q: "Notepad/WordPad’дан жакшыбы?", a: "Көп түзмөктөн жетүү жана бөлүшүү сыяктуу заманбап мүмкүнчүлүктөрдү берет." },
  { q: "Негизги мүмкүнчүлүктөрү кандай?", a: "Таза редактор, auto-save, online storage жана жеңил бөлүшүү." },
  { q: "Документ жазууга болобу?", a: "Ооба, жазуулар, драфттар жана жөнөкөй документтер үчүн ылайыктуу." },
  { q: "Текст форматтоону колдойбу?", a: "Негизги форматтоо параметрлери болушу мүмкүн." },
  { q: "Башка редакторлордон эмнеси менен айырмаланат?", a: "Жөнөкөйлүк, ылдамдык жана алаксытпаган жазууга басым жасайт." },
];

const TG_FAQS: FaqItem[] = [
  { q: "Notepad Online чист?", a: "Notepad Online муҳаррири матн дар браузер аст, ки бе насбкунӣ навиштан, таҳрир кардан ва захираро имкон медиҳад." },
  { q: "Notepad Online ройгон аст?", a: "Бале, пурра ройгон аст ва хароҷоти пинҳонӣ надорад." },
  { q: "Барои истифода бақайдгирӣ лозим аст?", a: "Не, шумо метавонед бе ҳисоб фавран оғоз кунед." },
  { q: "Метавонам қайдҳоро онлайн захира кунам?", a: "Бале, қайдҳоро захира карда, баъдтар боз мекушоед." },
  { q: "Auto-save дорад?", a: "Бале, ҳангоми навиштан худкор захира мешавад." },
  { q: "Аз дастгоҳҳои гуногун дастрас аст?", a: "Бале, аз телефон, планшет ва компютер." },
  { q: "Маълумоти ман бехатар аст?", a: "Бале, барои ҳифзи мундариҷа чораҳои махфият истифода мешаванд." },
  { q: "Метавонам қайдҳоро мубодила кунам?", a: "Бале, тавассути пайванди мубодила осон аст." },
  { q: "Дар мобил кор мекунад?", a: "Бале, интерфейс responsive ва барои мобил мувофиқ аст." },
  { q: "Офлайн кор мекунад?", a: "Баъзе имконот кор карда метавонанд, аммо барои захира ва ҳамоҳангсозӣ интернет тавсия мешавад." },
  { q: "Аз Notepad/WordPad беҳтар аст?", a: "Имкониятҳои муосир, мисли дастрасӣ аз чанд дастгоҳ ва мубодила медиҳад." },
  { q: "Имкониятҳои асосӣ кадомҳоянд?", a: "Муҳаррири тоза, auto-save, online storage ва мубодилаи осон." },
  { q: "Барои навиштани ҳуҷҷат мувофиқ аст?", a: "Бале, барои қайд, draft ва ҳуҷҷатҳои содда мувофиқ аст." },
  { q: "Оё форматбандии матнро дастгирӣ мекунад?", a: "Имкониятҳои асосии форматбандӣ метавонанд дастрас бошанд." },
  { q: "Аз дигар муҳаррирҳо чӣ фарқ дорад?", a: "Ба соддагӣ, суръат ва навиштани бе парешонӣ тамаркуз мекунад." },
];

const TK_FAQS: FaqItem[] = [
  { q: "Notepad Online näme?", a: "Notepad Online brauzerde işleýän tekst redaktory bolup, gurnamazdan ýazmaga, redaktirlemäge we saklamaga mümkinçilik berýär." },
  { q: "Notepad Online mugtmy?", a: "Hawa, doly mugt we gizlin tölegsiz." },
  { q: "Ulanyp başlamak üçin hasaba alynmak gerekmi?", a: "Ýok, hasapsyz derrew başlap bilersiňiz." },
  { q: "Bellikleri onlaýn saklap bolýarmy?", a: "Hawa, bellikler saklanyp, soňra täzeden açylyp bilner." },
  { q: "Auto-save barmy?", a: "Hawa, ýazanyňyzda awtomatiki saklanýar." },
  { q: "Dürli enjamlardan girip bolýarmy?", a: "Hawa, telefon, planşet we kompýuterden." },
  { q: "Maglumatlarym howpsuzmy?", a: "Hawa, mazmuny goramak üçin gizlinlik çäreleri ulanylýar." },
  { q: "Bellikleri paýlaşyp bolýarmy?", a: "Hawa, paýlaşma salgysy arkaly aňsat." },
  { q: "Mobilde işleýärmi?", a: "Hawa, mobil üçin responsive interfeýs bar." },
  { q: "Offline işleýärmi?", a: "Käbir funksiýalar işläp biler, ýöne saklamak we sinhronlamak üçin internet maslahat berilýär." },
  { q: "Notepad/WordPad-den gowumy?", a: "Köp enjamdan giriş we paýlaşma ýaly häzirki zaman aýratynlyklary bar." },
  { q: "Esasy aýratynlyklary nämeler?", a: "Arassa redaktor, auto-save, online storage we aňsat paýlaşma." },
  { q: "Resminama ýazmaga bolýarmy?", a: "Hawa, bellikler, draftlar we ýönekeý resminamalar üçin amatly." },
  { q: "Text formatting goldaýarmy?", a: "Esasy formatting mümkinçilikleri bar bolup biler." },
  { q: "Beýleki redaktorlardan tapawudy näme?", a: "Ýönekeýlik, tizlik we ünsüňi bölmeýän ýazuw tejribesine üns berýär." },
];

const PS_FAQS: FaqItem[] = [
  { q: "Notepad Online څه شی دی؟", a: "Notepad Online یو براوزر-بنسټ متن ایډیټر دی چې پرته له نصب څخه لیکل، سمول او خوندي کول اسانه کوي." },
  { q: "ایا Notepad Online وړیا دی؟", a: "هو، په بشپړ ډول وړیا دی او پټ لګښتونه نه لري." },
  { q: "د کارولو لپاره نوم‌لیکنه ضروري ده؟", a: "نه، له حساب پرته هم سمدستي کارولای شئ." },
  { q: "ایا یادښتونه آنلاین خوندي کېدای شي؟", a: "هو، یادښتونه خوندي کېږي او وروسته بیا پرانیستل کېدای شي." },
  { q: "Auto-save لري؟", a: "هو، د لیکلو پر مهال په اوتومات ډول خوندي کېږي." },
  { q: "له بېلابېلو وسیلو څخه لاسرسی شته؟", a: "هو، له موبایل، ټابلېټ او کمپیوټر څخه." },
  { q: "زما معلومات خوندي دي؟", a: "هو، د منځپانګې د ساتنې لپاره د محرمیت تدابیر کارول کېږي." },
  { q: "ایا یادښتونه شریکولای شم؟", a: "هو، د شریکولو لینک له لارې په اسانۍ." },
  { q: "په موبایل کې کار کوي؟", a: "هو، responsive او د موبایل لپاره مناسب دی." },
  { q: "ایا آفلاین کار کوي؟", a: "ځینې فیچرونه کېدای شي کار وکړي، خو د خوندي کولو او همغږۍ لپاره انټرنېټ غوره دی." },
  { q: "له Notepad/WordPad څخه ښه دی؟", a: "د څو وسیلو لاسرسی او شریکولو په څېر عصري ځانګړتیاوې لري." },
  { q: "اصلي ځانګړتیاوې کومې دي؟", a: "ساده ایډیټر، auto-save، online storage او اسانه شریکول." },
  { q: "د اسنادو لیکلو لپاره مناسب دی؟", a: "هو، د یادښتونو، مسودو او ساده اسنادو لپاره مناسب دی." },
  { q: "د متن format ملاتړ کوي؟", a: "بنسټیز formatting انتخابونه کېدای شي موجود وي." },
  { q: "له نورو ایډیټرونو څه توپیر لري؟", a: "پر سادګۍ، چټکتیا او بې‌حواسۍ لیکلو تمرکز کوي." },
];

const KU_FAQS: FaqItem[] = [
  { q: "Notepad Online çi ye?", a: "Notepad Online edîtorek nivîsê ya ser browser e ku bê sazkirinê nivîsandin, guherandin û parastinê hêsan dike." },
  { q: "Notepad Online belaş e?", a: "Erê, bi tevahî belaş e û xercên veşartî tune ne." },
  { q: "Ji bo bikaranînê qeyd lazim e?", a: "Na, bê hesab jî dikarî yekser dest pê bikî." },
  { q: "Dikarem notan online biparêzim?", a: "Erê, not tê parastin û paşê dibe ku dîsa were vekirin." },
  { q: "Auto-save heye?", a: "Erê, dema tu dinivîsî bi xwe tê parastin." },
  { q: "Ji amûrên cihê tê gihîştin?", a: "Erê, ji mobil, tablet û desktop." },
  { q: "Daneyên min ewle ne?", a: "Erê, ji bo parastina naverokê tedbîrên taybetmendiyê têne bikaranîn." },
  { q: "Dikarem notan parve bikim?", a: "Erê, bi linka parvekirinê re hêsan e." },
  { q: "Li ser mobil dixebite?", a: "Erê, responsive û mobil-friendly ye." },
  { q: "Offline dixebite?", a: "Hin taybetmendî dikarin bixebitin, lê ji bo parastin û sync internet baştir e." },
  { q: "Ji Notepad/WordPad çêtir e?", a: "Taybetmendiyên nûjen wekî gihîştina gelek-amûrî û parvekirinê pêşkêş dike." },
  { q: "Taybetmendiyên sereke çi ne?", a: "Edîtorek sade, auto-save, online storage û parvekirina hêsan." },
  { q: "Ji bo nivîsandina belgeyan baş e?", a: "Erê, ji bo not, draft û belgeyên hêsan guncan e." },
  { q: "Formatting-a tekstê destek dike?", a: "Dibe ku vebijarkên bingehîn ên formatting hebe." },
  { q: "Ji edîtorên din çawa cuda ye?", a: "Li ser sadetî, lez û nivîsandina bê tevliheviyê fokus dike." },
];

const SQ_FAQS: FaqItem[] = [
  { q: "Çfarë është Notepad Online?", a: "Notepad Online është një editor teksti në browser që ju lejon të shkruani, redaktoni dhe ruani pa instalim." },
  { q: "A është Notepad Online falas?", a: "Po, është plotësisht falas pa tarifa të fshehura." },
  { q: "A duhet të regjistrohem për ta përdorur?", a: "Jo, mund të filloni menjëherë pa llogari." },
  { q: "A mund t’i ruaj shënimet online?", a: "Po, shënimet mund të ruhen dhe hapen përsëri më vonë." },
  { q: "A ka auto-save?", a: "Po, ruhet automatikisht gjatë shkrimit." },
  { q: "A mund të hyj nga pajisje të ndryshme?", a: "Po, nga telefon, tablet dhe kompjuter." },
  { q: "A janë të sigurta të dhënat e mia?", a: "Po, përdoren masa privatësie për të mbrojtur përmbajtjen tuaj." },
  { q: "A mund të ndaj shënimet?", a: "Po, përmes një linku të ndashëm." },
  { q: "A funksionon në celular?", a: "Po, është responsive dhe i përshtatur për celular." },
  { q: "A funksionon offline?", a: "Disa funksione mund të punojnë, por interneti rekomandohet për ruajtje dhe sinkronizim." },
  { q: "A është më i mirë se Notepad/WordPad?", a: "Ofron veçori moderne si akses në shumë pajisje dhe ndarje." },
  { q: "Cilat janë veçoritë kryesore?", a: "Editor i pastër, auto-save, online storage dhe ndarje e lehtë." },
  { q: "A mund të shkruaj dokumente?", a: "Po, është i përshtatshëm për shënime, drafte dhe dokumente të thjeshta." },
  { q: "A mbështet formatimin e tekstit?", a: "Mund të ketë opsione bazë të formatimit." },
  { q: "Si ndryshon nga editorët e tjerë?", a: "Fokusohet te thjeshtësia, shpejtësia dhe shkrimi pa shpërqendrime." },
];

const HOME_FAQS_BY_LOCALE: Record<string, FaqItem[]> = {
  ar: AR_FAQS,
  es: ES_FAQS,
  fr: FR_FAQS,
  de: DE_FAQS,
  pt: PT_FAQS,
  zh: ZH_FAQS,
  hi: HI_FAQS,
  ru: RU_FAQS,
  ja: JA_FAQS,
  id: ID_FAQS,
  tr: TR_FAQS,
  bn: BN_FAQS,
  ur: UR_FAQS,
  ko: KO_FAQS,
  vi: VI_FAQS,
  it: IT_FAQS,
  fa: FA_FAQS,
  th: TH_FAQS,
  nl: NL_FAQS,
  sv: SV_FAQS,
  pl: PL_FAQS,
  cs: CS_FAQS,
  ro: RO_FAQS,
  hu: HU_FAQS,
  he: HE_FAQS,
  da: DA_FAQS,
  fi: FI_FAQS,
  no: NO_FAQS,
  sk: SK_FAQS,
  bg: BG_FAQS,
  hr: HR_FAQS,
  sr: SR_FAQS,
  uk: UK_FAQS,
  ta: TA_FAQS,
  te: TE_FAQS,
  mr: MR_FAQS,
  gu: GU_FAQS,
  kn: KN_FAQS,
  ml: ML_FAQS,
  si: SI_FAQS,
  ne: NE_FAQS,
  ms: MS_FAQS,
  sw: SW_FAQS,
  af: AF_FAQS,
  am: AM_FAQS,
  so: SO_FAQS,
  yo: YO_FAQS,
  ig: IG_FAQS,
  ha: HA_FAQS,
  uz: UZ_FAQS,
  kk: KK_FAQS,
  ky: KY_FAQS,
  tg: TG_FAQS,
  tk: TK_FAQS,
  ps: PS_FAQS,
  ku: KU_FAQS,
  sq: SQ_FAQS,
};

export function getHomeFaqs(locale: string): FaqItem[] {
  return HOME_FAQS_BY_LOCALE[locale] ?? EN_FAQS;
}

export function getHomeFaqJsonLd(locale: string) {
  const faqs = getHomeFaqs(locale);
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.a,
      },
    })),
  };
}
