/** Short blurb under the footer logo (per locale). */

const en =
  "Notepad Online is a free note-taking tool to write, edit, and store notes online. Share your notes easily and access them anytime, anywhere.";

const byLocale: Record<string, string> = {
  en,
  zh: "在线记事本是一款免费的笔记工具，可在线编写、编辑和保存笔记。您可以轻松分享笔记并随时随地访问。",
  es: "Notepad Online es una herramienta gratuita para tomar notas, escribir, editar y guardar notas en línea. Comparte tus notas fácilmente y accede a ellas en cualquier momento y lugar.",
  ar: "المفكرة أونلاين هي أداة مجانية لتدوين الملاحظات وكتابتها وتحريرها وحفظها عبر الإنترنت. يمكنك مشاركة ملاحظاتك بسهولة والوصول إليها في أي وقت ومن أي مكان.",
  id: "Notepad Online adalah alat pencatat gratis untuk menulis, mengedit, dan menyimpan catatan secara online. Bagikan catatan Anda dengan mudah dan akses kapan saja di mana saja.",
  pt: "O Notepad Online é uma ferramenta gratuita para escrever, editar e armazenar notas online. Compartilhe suas notas facilmente e acesse a qualquer hora e lugar.",
  fr: "Notepad Online est un outil gratuit de prise de notes pour écrire, modifier et stocker des notes en ligne. Partagez facilement vos notes et accédez-y à tout moment, où que vous soyez.",
  ja: "Notepad Onlineは、オンラインでメモを作成・編集・保存できる無料のノートツールです。メモを簡単に共有し、いつでもどこでもアクセスできます。",
  ru: "Notepad Online: это бесплатный инструмент для создания, редактирования и хранения заметок онлайн. Легко делитесь заметками и получайте доступ к ним в любое время и в любом месте.",
  de: "Notepad Online ist ein kostenloses Notiz-Tool zum Schreiben, Bearbeiten und Speichern von Notizen online. Teile deine Notizen einfach und greife jederzeit und überall darauf zu.",
  hi: "Notepad Online एक मुफ्त नोट लेने का टूल है जिससे आप ऑनलाइन नोट लिख, संपादित और स्टोर कर सकते हैं। अपने नोट्स आसानी से साझा करें और कभी भी, कहीं भी एक्सेस करें।",
  bn: "Notepad Online একটি ফ্রি নোট নেওয়ার টুল, যেখানে আপনি অনলাইনে নোট লিখতে, সম্পাদনা করতে এবং সংরক্ষণ করতে পারেন। সহজেই আপনার নোট শেয়ার করুন এবং যেকোনো সময়, যেকোনো জায়গা থেকে অ্যাক্সেস করুন।",
  ur: "Notepad Online ایک مفت نوٹ لینے کا ٹول ہے جس سے آپ آن لائن نوٹس لکھ، ایڈٹ اور محفوظ کر سکتے ہیں۔ اپنے نوٹس آسانی سے شیئر کریں اور کہیں بھی، کسی بھی وقت رسائی حاصل کریں۔",
  tr: "Notepad Online, notlarınızı çevrimiçi yazmak, düzenlemek ve saklamak için ücretsiz bir araçtır. Notlarınızı kolayca paylaşın ve istediğiniz zaman, istediğiniz yerden erişin.",
  ko: "Notepad Online은 온라인에서 메모를 작성, 편집 및 저장할 수 있는 무료 노트 도구입니다. 메모를 쉽게 공유하고 언제 어디서나 접근할 수 있습니다.",
  vi: "Notepad Online là công cụ ghi chú miễn phí giúp bạn viết, chỉnh sửa và lưu trữ ghi chú trực tuyến. Dễ dàng chia sẻ ghi chú và truy cập mọi lúc, mọi nơi.",
  it: "Notepad Online è uno strumento gratuito per prendere appunti, scrivere, modificare e salvare note online. Condividi facilmente le tue note e accedi ovunque e in qualsiasi momento.",
  fa: "Notepad Online یک ابزار رایگان برای یادداشت‌برداری است که به شما امکان نوشتن، ویرایش و ذخیره آنلاین یادداشت‌ها را می‌دهد. به‌راحتی یادداشت‌های خود را به اشتراک بگذارید و هر زمان و هر مکان به آن‌ها دسترسی داشته باشید.",
  th: "Notepad Online คือเครื่องมือจดบันทึกฟรีสำหรับเขียน แก้ไข และจัดเก็บโน้ตออนไลน์ แชร์โน้ตของคุณได้ง่ายและเข้าถึงได้ทุกที่ทุกเวลา",
  pl: "Notepad Online to darmowe narzędzie do robienia notatek, pisania, edytowania i przechowywania ich online. Udostępniaj notatki łatwo i uzyskuj do nich dostęp w dowolnym miejscu i czasie.",
  nl: "Notepad Online is een gratis notitie-tool om notities online te schrijven, bewerken en opslaan. Deel je notities eenvoudig en krijg overal en altijd toegang.",
  sv: "Notepad Online är ett gratis anteckningsverktyg för att skriva, redigera och lagra anteckningar online. Dela dina anteckningar enkelt och få åtkomst när som helst, var som helst.",
  el: "Το Notepad Online είναι ένα δωρεάν εργαλείο σημειώσεων για να γράφετε, να επεξεργάζεστε και να αποθηκεύετε σημειώσεις online. Μοιραστείτε εύκολα τις σημειώσεις σας και αποκτήστε πρόσβαση οποτεδήποτε και οπουδήποτε.",
  cs: "Notepad Online je bezplatný nástroj pro psaní, úpravu a ukládání poznámek online. Snadno sdílejte své poznámky a přistupujte k nim kdykoli a kdekoli.",
  ro: "Notepad Online este un instrument gratuit pentru luarea de notițe, scriere, editare și stocare online. Distribuie ușor notițele și accesează-le oricând, oriunde.",
  hu: "A Notepad Online egy ingyenes jegyzetelő eszköz, amellyel online írhatsz, szerkeszthetsz és tárolhatsz jegyzeteket. Könnyen megoszthatod jegyzeteidet és bármikor, bárhol elérheted őket.",
  he: "Notepad Online הוא כלי חינמי לרישום, עריכה ושמירת הערות אונליין. שתף את ההערות שלך בקלות וגשת אליהן בכל זמן ומקום.",
  da: "Notepad Online er et gratis noteværktøj til at skrive, redigere og gemme noter online. Del dine noter nemt og få adgang når som helst, hvor som helst.",
  fi: "Notepad Online on ilmainen muistiinpanotyökalu, jolla voit kirjoittaa, muokata ja tallentaa muistiinpanoja verkossa. Jaa muistiinpanosi helposti ja käytä niitä missä ja milloin tahansa.",
  no: "Notepad Online er et gratis notatverktøy for å skrive, redigere og lagre notater på nett. Del notatene dine enkelt og få tilgang når som helst og hvor som helst.",
  sk: "Notepad Online je bezplatný nástroj na písanie, úpravu a ukladanie poznámok online. Jednoducho zdieľajte svoje poznámky a pristupujte k nim kedykoľvek a kdekoľvek.",
  bg: "Notepad Online е безплатен инструмент за водене, редактиране и съхранение на бележки онлайн. Лесно споделяйте бележките си и имайте достъп по всяко време и навсякъде.",
  hr: "Notepad Online je besplatan alat za pisanje, uređivanje i spremanje bilješki online. Jednostavno dijelite bilješke i pristupajte im bilo kada i bilo gdje.",
  sr: "Notepad Online je besplatan alat za pisanje, uređivanje i čuvanje beleški online. Lako delite svoje beleške i pristupajte im bilo kada i bilo gde.",
  uk: "Notepad Online: це безкоштовний інструмент для створення, редагування та зберігання нотаток онлайн. Легко діліться нотатками та отримуйте доступ будь-коли і будь-де.",
  ta: "Notepad Online என்பது இலவச குறிப்பு எடுக்கும் கருவி ஆகும், இதில் நீங்கள் ஆன்லைனில் குறிப்புகளை எழுத, திருத்த மற்றும் சேமிக்கலாம். உங்கள் குறிப்புகளை எளிதாக பகிர்ந்து எப்போது வேண்டுமானாலும் எங்கிருந்தும் அணுகலாம்.",
  te: "Notepad Online అనేది ఉచిత నోట్-టేకింగ్ టూల్, దీని ద్వారా మీరు ఆన్‌లైన్‌లో నోట్స్ రాయవచ్చు, ఎడిట్ చేయవచ్చు మరియు నిల్వ చేయవచ్చు. మీ నోట్స్‌ను సులభంగా పంచుకోండి మరియు ఎప్పుడైనా, ఎక్కడైనా యాక్సెస్ చేయండి.",
  mr: "Notepad Online हे एक मोफत नोट घेण्याचे साधन आहे ज्याद्वारे तुम्ही ऑनलाइन नोट्स लिहू, संपादित करू आणि साठवू शकता. तुमच्या नोट्स सहज शेअर करा आणि कधीही, कुठेही प्रवेश करा.",
  gu: "Notepad Online એક મફત નોટ લેવાનું સાધન છે, જેમાં તમે ઓનલાઇન નોટ્સ લખી, સંપાદિત અને સંગ્રહ કરી શકો છો. તમારી નોટ્સ સરળતાથી શેર કરો અને ક્યારે પણ, ક્યાં પણ ઍક્સેસ કરો.",
  kn: "Notepad Online ಒಂದು ಉಚಿತ ನೋಟ್ಸ್ ತೆಗೆದುಕೊಳ್ಳುವ ಸಾಧನವಾಗಿದ್ದು, ಇದರಲ್ಲಿ ನೀವು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ನೋಟ್ಸ್ ಬರೆಯಬಹುದು, ಸಂಪಾದಿಸಬಹುದು ಮತ್ತು ಸಂಗ್ರಹಿಸಬಹುದು. ನಿಮ್ಮ ನೋಟ್ಸ್ ಅನ್ನು ಸುಲಭವಾಗಿ ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ಯಾವುದೇ ಸಮಯದಲ್ಲಿ, ಎಲ್ಲಿಂದ ಬೇಕಾದರೂ ಪ್ರವೇಶಿಸಬಹುದು.",
  ml: "Notepad Online ഒരു സൗജന്യ നോട്ട് എടുക്കൽ ഉപകരണമാണ്, ഇതിലൂടെ നിങ്ങൾക്ക് ഓൺലൈനിൽ നോട്ടുകൾ എഴുതാനും തിരുത്താനും സംഭരിക്കാനും കഴിയും. നിങ്ങളുടെ നോട്ടുകൾ എളുപ്പത്തിൽ പങ്കിടുക, എപ്പോഴും എവിടെയും ആക്‌സസ് ചെയ്യുക.",
  si: "Notepad Online යනු නොමිලේ ලබාදෙන සටහන් තැබීමේ මෙවලමකි. ඔබට ඔන්ලයින් සටහන් ලිවීමට, සංස්කරණය කිරීමට සහ ගබඩා කිරීමට හැකිය. ඔබගේ සටහන් පහසුවෙන් බෙදාගන්න සහ ඕනෑම වේලාවක, ඕනෑම තැනක ප්‍රවේශ වන්න.",
  ne: "Notepad Online एक नि:शुल्क नोट लेख्ने उपकरण हो, जसले तपाईंलाई अनलाइन नोट लेख्न, सम्पादन गर्न र भण्डारण गर्न अनुमति दिन्छ। आफ्ना नोटहरू सजिलै सेयर गर्नुहोस् र जुनसुकै समय, जुनसुकै स्थानबाट पहुँच गर्नुहोस्।",
  my: "Notepad Online သည် အခမဲ့ မှတ်စုရေးကိရိယာတစ်ခုဖြစ်ပြီး အွန်လိုင်းတွင် မှတ်စုရေး၊ တည်းဖြတ်နှင့် သိမ်းဆည်းနိုင်သည်။ သင့်မှတ်စုများကို လွယ်ကူစွာ မျှဝေပြီး မည်သည့်အချိန်၊ မည်သည့်နေရာမှမဆို အသုံးပြုနိုင်သည်။",
  km: "Notepad Online គឺជាឧបករណ៍កំណត់ចំណាំឥតគិតថ្លៃ ដែលអាចឱ្យអ្នកសរសេរ កែសម្រួល និងរក្សាទុកចំណាំតាមអ៊ីនធឺណិតបាន។ អ្នកអាចចែករំលែកចំណាំរបស់អ្នកបានយ៉ាងងាយស្រួល និងចូលប្រើបានគ្រប់ពេលគ្រប់ទីកន្លែង។",
  lo: "Notepad Online ແມ່ນເຄື່ອງມືບັນທຶກຟຣີ ທີ່ຊ່ວຍໃຫ້ທ່ານຂຽນ, ແກ້ໄຂ ແລະ ເກັບຮັກສາບັນທຶກອອນລາຍ. ແບ່ງປັນບັນທຶກຂອງທ່ານໄດ້ງ່າຍ ແລະ ເຂົ້າເຖິງໄດ້ທຸກເວລາທຸກສະຖານທີ່.",
  mn: "Notepad Online нь үнэгүй тэмдэглэл хөтлөх хэрэгсэл бөгөөд онлайнаар бичих, засварлах, хадгалах боломжтой. Тэмдэглэлээ амархан хуваалцаж, хүссэн үедээ хаанаас ч хандаарай.",
  ka: "Notepad Online არის უფასო ჩანაწერების ინსტრუმენტი, რომელიც საშუალებას გაძლევთ ონლაინ დაწეროთ, დაარედაქტიროთ და შეინახოთ ჩანაწერები. მარტივად გააზიარეთ თქვენი ჩანაწერები და წვდომა გქონდეთ ნებისმიერ დროს, ნებისმიერ ადგილას.",
  hy: "Notepad Online-ը անվճար գրառումների գործիք է, որը թույլ է տալիս առցանց գրել, խմբագրել և պահել գրառումներ։ Հեշտությամբ կիսվեք ձեր գրառումներով և հասանելի եղեք ցանկացած ժամանակ, ցանկացած վայրում։",
  az: "Notepad Online pulsuz qeyd aparma vasitəsidir, onlayn yazmaq, redaktə etmək və saxlamaq üçün istifadə olunur. Qeydlərinizi asanlıqla paylaşın və istənilən vaxt, istənilən yerdə daxil olun.",
  sw: "Notepad Online ni zana ya bure ya kuandika, kuhariri na kuhifadhi maelezo mtandaoni. Shiriki maelezo yako kwa urahisi na yafikie wakati wowote, mahali popote.",
  zu: "Notepad Online iyithuluzi lamahhala lokubhala amanothi, ukuhlela nokugcina amanothi ku-inthanethi. Yabelana kalula futhi ufinyelele noma nini, noma kuphi.",
  af: "Notepad Online is ’n gratis notas-instrument om notas aanlyn te skryf, te redigeer en te stoor. Deel jou notas maklik en kry toegang enige tyd en enige plek.",
  am: "Notepad Online ነፃ የማስታወሻ መሳሪያ ነው፣ በመስመር ላይ ማስታወሻ መጻፍ፣ ማስተካከል እና ማስቀመጥ ይፈቅዳል። ማስታወሻዎችዎን በቀላሉ ያጋሩ እና በማንኛውም ጊዜ ከማንኛውም ቦታ ይድረሱ።",
  so: "Notepad Online waa qalab bilaash ah oo lagu qoro, lagu tafatiro laguna kaydiyo qoraallo online ah. Si fudud u wadaag qoraaladaada oo ka hel mar kasta iyo meel kasta.",
  yo: "Notepad Online jẹ irinṣẹ ọfẹ fun kikọ, ṣiṣatunkọ ati titoju akọsilẹ lori ayelujara. Pin akọsilẹ rẹ ni rọọrun ki o wọle si nigbakugba, nibikibi.",
  ig: "Notepad Online bụ ngwa efu maka ide, dezie na chekwaa ndetu n’ịntanetị. Kesaa ndetu gị mfe ma nweta ya mgbe ọ bụla, ebe ọ bụla.",
  ha: "Notepad Online kayan rubutu ne na kyauta don rubuta, gyarawa da adana bayanai a yanar gizo. Raba bayananka cikin sauƙi kuma ka sami damar shiga a kowane lokaci.",
  mg: "Notepad Online dia fitaovana maimaim-poana hanoratana, hanovana ary hitahirizana naoty an-tserasera. Zarao mora ny naotinao ary midira amin’ny fotoana sy toerana rehetra.",
  uz: "Notepad Online bepul eslatma yozish vositasi bo‘lib, onlayn yozish, tahrirlash va saqlash imkonini beradi. Eslatmalaringizni oson ulashing va istalgan vaqtda, istalgan joyda foydalaning.",
  kk: "Notepad Online – бұл онлайн жазуға, өңдеуге және сақтауға арналған тегін жазба құралы. Жазбаларыңызды оңай бөлісіп, кез келген уақытта, кез келген жерден қол жеткізіңіз.",
  ky: "Notepad Online – бул онлайн жазуу, түзөтүү жана сактоо үчүн акысыз жазуу куралы. Жазмаларыңызды оңой бөлүшүп, каалаган убакта, каалаган жерден кире аласыз.",
  tg: "Notepad Online як воситаи ройгони қайдкунӣ аст, ки ба шумо имкон медиҳад онлайн нависед, таҳрир кунед ва захира намоед. Қайдҳои худро осон мубодила кунед ва ҳар вақт дастрас шавед.",
  tk: "Notepad Online – bu onlaýn ýazmak, redaktirlemek we saklamak üçin mugt ýazgy guralydyr. Bellikleriňizi aňsat paýlaşyň we islendik wagtda girip bilersiňiz.",
  ps: "Notepad Online یو وړیا د نوټ اخیستلو وسیله ده چې تاسو ته اجازه درکوي آنلاین نوټونه ولیکئ، سم کړئ او وساتئ. خپل نوټونه په اسانۍ شریک کړئ او هر وخت، هر ځای لاسرسی وکړئ.",
  ku: "Notepad Online amûrek belaş e ji bo nivîsîn, guherandin û hilanînê. Notên xwe hêsan parve bikin û her dem, her der bikevin.",
  sq: "Notepad Online është një mjet falas për shënime që ju lejon të shkruani, redaktoni dhe ruani shënime online. Ndani lehtë shënimet dhe aksesoni ato në çdo kohë, kudo.",
  lt: "Notepad Online yra nemokamas užrašų įrankis, leidžiantis rašyti, redaguoti ir saugoti užrašus internete. Lengvai dalinkitės užrašais ir pasiekite juos bet kada ir bet kur.",
  lv: "Notepad Online ir bezmaksas piezīmju rīks, kas ļauj rakstīt, rediģēt un glabāt piezīmes tiešsaistē. Viegli kopīgojiet piezīmes un piekļūstiet tām jebkurā laikā un vietā.",
  et: "Notepad Online on tasuta märkmete tööriist, mis võimaldab kirjutada, redigeerida ja salvestada märkmeid veebis. Jaga oma märkmeid lihtsalt ja pääse neile ligi igal ajal ja igal pool.",
  is: "Notepad Online er ókeypis glósutól til að skrifa, breyta og geyma glósur á netinu. Deildu glósum auðveldlega og fáðu aðgang hvenær sem er og hvar sem er.",
  ga: "Is uirlis nótaí saor in aisce é Notepad Online chun nótaí a scríobh, a chur in eagar agus a stóráil ar líne. Roinn do chuid nótaí go héasca agus faigh rochtain orthu am ar bith, áit ar bith.",
  cy: "Mae Notepad Online yn offeryn nodiadau am ddim i ysgrifennu, golygu a storio nodiadau ar-lein. Rhannwch eich nodiadau’n hawdd a chael mynediad unrhyw bryd, unrhyw le.",
  eu: "Notepad Online doako ohar-tresna bat da, oharrak idatzi, editatu eta online gordetzeko aukera ematen duena. Partekatu zure oharrak erraz eta sartu edozein unetan.",
  ca: "Notepad Online és una eina gratuïta per escriure, editar i emmagatzemar notes en línia. Comparteix les teves notes fàcilment i accedeix-hi en qualsevol moment i lloc.",
  gl: "Notepad Online é unha ferramenta gratuíta para escribir, editar e gardar notas en liña. Comparte as túas notas facilmente e accede a elas en calquera momento e lugar.",
  mt: "Notepad Online hija għodda b’xejn biex tikteb, teditja u taħżen noti online. Aqsam in-noti tiegħek faċilment u aċċessahom kull ħin u kullimkien.",
  lb: "Notepad Online ass e gratis Notiz-Tool fir Notizen online ze schreiwen, z’änneren an ze späicheren. Deelt Är Notizen einfach a gräift zu hinnen zu all Zäit a Plaz.",
  mk: "Notepad Online е бесплатна алатка за белешки што овозможува пишување, уредување и зачувување белешки онлајн. Лесно споделувајте и пристапувајте во секое време и на секое место.",
  bs: "Notepad Online je besplatan alat za bilješke koji omogućava pisanje, uređivanje i spremanje bilješki online. Lako dijelite i pristupajte u bilo koje vrijeme i bilo gdje.",
  sl: "Notepad Online je brezplačno orodje za beležke, ki omogoča pisanje, urejanje in shranjevanje zapiskov na spletu. Z lahkoto delite zapiske in dostopate kadar koli in kjer koli.",
  fj: "Notepad Online e dua na tool ni volavola sega ni saumi me vola, veisautaka ka maroroya na notes ena internet. Vakarautaka rawarawa nomu notes ka curu kina ena gauna cava ga.",
  mi: "Ko Notepad Online he taputapu tuhipoka kore utu hei tuhi, whakatika, me te penapena tuhipoka ā-ipurangi. Tiri i ō tuhipoka me te uru i ngā wā katoa, i ngā wāhi katoa.",
  sm: "Notepad Online o se meafaigaluega e leai se totogi e tusitusi ai, faasaʻo ma teu ai faamaumauga i luga o le initaneti. Faasoa faigofie au faamaumauga ma maua i soo se taimi, soo se nofoaga.",
  to: "Notepad Online ko ha me’angaue ta’etotongi ki he tohi, fakatonutonu mo e tauhi ngaahi noti ‘i he ‘initaneti. Vahevahe faingofua ho’o noti pea ma’u ‘i he taimi kotoa pē.",
  ht: "Notepad Online se yon zouti gratis pou ekri, modifye epi sove nòt sou entènèt. Pataje nòt ou fasil epi jwenn aksè nenpòt ki lè, nenpòt kote.",
  qu: "Notepad Onlineqa mana qullqiyuq qillqana, ruwana, chaymanta waqaychana internetpi. Qillqaykikunata allinllata rakinaykiku, ima pachapi ima maypipas yaykuy.",
  ay: "Notepad Online ukaxa mä qillqaña herramienta gratuita ukawa, internet tuqina qillqaña, askichaña ukhamaraki imaña. Qillqatanakamaruxa jank’aki uñt’ayaña ukhamaraki kawkipachasa mantasma.",
  gn: "Notepad Online ha’e peteĩ tembiporu gratis ojehai hag̃ua, oñemyatyrõ hag̃ua ha oñeñongatu hag̃ua internet rupive. Eñemoĩ ne notakuéra ha eike oimeraẽ hendápe, oimeraẽ aravo.",
  nv: "Notepad Online t’áá ajiłii’ígíí notetool yáhoot’ééł doo béésh bee shikaad. Níłch’i’í t’áá ajiłii’ígíí yazhííł, doo baa hane’ígíí bee nitsáhákees.",
  iu: "Notepad Online tassaavoq akiitsoq allattuisarfik, internet-ikkut allattuisinnaaneq, allannguisinnaaneq aammalu toqqorsineq periarfissallit. Allakkatit siammarterlugit sumiiffinni tamani atorneqarsinnaapput.",
  kl: "Notepad Online tassaavoq akeqanngitsoq allattuut, internetsikkut allattornissamut, allannguinissamut aammalu toqqorsinermut atorneqartoq. Allattuutitit ajornanngitsumik siammarteriarlugit atorneqarsinnaapput.",
  om: "Notepad Online jechuun meeshaa bilisaa barreessuu, gulaaluu fi kuusuu kan internet irratti hojjetu dha. Barreeffamoota kee salphaatti qoodiitii yeroo kamiyyuu, bakka kamittuu argadhu.",
  ti: "Notepad Online ነፃ መሳርሒ ጽሑፍ እዩ፣ በመስመር ላይ ምጽሓፍ፣ ምትካእ እና ምሕዳስ ይፈቅድ። ማስታወሻታትካ ብቀሊሉ ኣካፍል እና ኣብ ዝኾነ ጊዜ ተጠቀም።",
  sn: "Notepad Online chishandiso chemahara chekunyora, kugadzirisa nekuchengetedza manotsi paInternet. Govera manotsi ako zviri nyore uye shandisa chero nguva, chero kupi.",
  xh: "Notepad Online sisixhobo samahala sokubhala, ukuhlela nokugcina amanqaku kwi-intanethi. Yabelana amanqaku akho lula kwaye uwafikelele nanini na naphi na.",
  ceb: "Ang Notepad Online usa ka libre nga himan sa pagsulat, pag-edit ug pagtipig og notes online. Ipaambit ang imong notes ug ma-access bisan kanus-a ug bisan asa.",
  tl: "Ang Notepad Online ay isang libreng tool sa pagsusulat, pag-edit at pag-iimbak ng notes online. Ibahagi ang iyong notes at ma-access kahit kailan at kahit saan.",
  jv: "Notepad Online yaiku alat gratis kanggo nulis, nyunting lan nyimpen cathetan online. Nuduhake cathetan kanthi gampang lan akses kapan wae lan ing ngendi wae.",
  su: "Notepad Online nyaéta alat gratis pikeun nulis, ngédit, jeung nyimpen catetan online. Bagikeun catetan anjeun kalayan gampang sareng aksés iraha waé sareng dimana waé.",
};

export function getFooterTagline(locale: string): string {
  return byLocale[locale] ?? en;
}
