/** Main site nav link labels (locale → strings). Missing locales fall back to English. */

export type NavLabels = {
  notepad: string;
  writingTools: string;
  blog: string;
  about: string;
  contact: string;
  privacy: string;
};

const en: NavLabels = {
  notepad: "Notepad",
  writingTools: "Writing Tools",
  blog: "Blog",
  about: "About",
  contact: "Contact",
  privacy: "Privacy",
};

const byLocale: Record<string, NavLabels> = {
  en,
  zh: {
    notepad: "记事本",
    writingTools: "写作工具",
    blog: "博客",
    about: "关于",
    contact: "联系",
    privacy: "隐私",
  },
  es: {
    notepad: "Bloc de notas",
    writingTools: "Herramientas de escritura",
    blog: "Blog",
    about: "Acerca de",
    contact: "Contacto",
    privacy: "Privacidad",
  },
  ar: {
    notepad: "المفكرة",
    writingTools: "أدوات الكتابة",
    blog: "مدونة",
    about: "حول",
    contact: "اتصال",
    privacy: "الخصوصية",
  },
  id: {
    notepad: "Notepad",
    writingTools: "Alat Menulis",
    blog: "Blog",
    about: "Tentang",
    contact: "Kontak",
    privacy: "Privasi",
  },
  pt: {
    notepad: "Bloco de notas",
    writingTools: "Ferramentas de escrita",
    blog: "Blog",
    about: "Sobre",
    contact: "Contato",
    privacy: "Privacidade",
  },
  fr: {
    notepad: "Bloc-notes",
    writingTools: "Outils d’écriture",
    blog: "Blog",
    about: "À propos",
    contact: "Contact",
    privacy: "Confidentialité",
  },
  ja: {
    notepad: "メモ帳",
    writingTools: "ライティングツール",
    blog: "ブログ",
    about: "概要",
    contact: "お問い合わせ",
    privacy: "プライバシー",
  },
  ru: {
    notepad: "Блокнот",
    writingTools: "Инструменты для письма",
    blog: "Блог",
    about: "О нас",
    contact: "Контакты",
    privacy: "Конфиденциальность",
  },
  de: {
    notepad: "Notizblock",
    writingTools: "Schreibwerkzeuge",
    blog: "Blog",
    about: "Über uns",
    contact: "Kontakt",
    privacy: "Datenschutz",
  },
  hi: {
    notepad: "नोटपैड",
    writingTools: "लेखन उपकरण",
    blog: "ब्लॉग",
    about: "हमारे बारे में",
    contact: "संपर्क",
    privacy: "गोपनीयता",
  },
  bn: {
    notepad: "নোটপ্যাড",
    writingTools: "লেখার টুলস",
    blog: "ব্লগ",
    about: "সম্পর্কে",
    contact: "যোগাযোগ",
    privacy: "গোপনীয়তা",
  },
  ur: {
    notepad: "نوٹ پیڈ",
    writingTools: "تحریری ٹولز",
    blog: "بلاگ",
    about: "ہمارے بارے میں",
    contact: "رابطہ",
    privacy: "پرائیویسی",
  },
  tr: {
    notepad: "Not Defteri",
    writingTools: "Yazma Araçları",
    blog: "Blog",
    about: "Hakkında",
    contact: "İletişim",
    privacy: "Gizlilik",
  },
  ko: {
    notepad: "메모장",
    writingTools: "글쓰기 도구",
    blog: "블로그",
    about: "소개",
    contact: "연락처",
    privacy: "개인정보",
  },
  vi: {
    notepad: "Sổ ghi chú",
    writingTools: "Công cụ viết",
    blog: "Blog",
    about: "Giới thiệu",
    contact: "Liên hệ",
    privacy: "Quyền riêng tư",
  },
  it: {
    notepad: "Blocco note",
    writingTools: "Strumenti di scrittura",
    blog: "Blog",
    about: "Chi siamo",
    contact: "Contatto",
    privacy: "Privacy",
  },
  fa: {
    notepad: "نوت‌پد",
    writingTools: "ابزارهای نوشتن",
    blog: "وبلاگ",
    about: "درباره ما",
    contact: "تماس",
    privacy: "حریم خصوصی",
  },
  th: {
    notepad: "โน้ตแพด",
    writingTools: "เครื่องมือเขียน",
    blog: "บล็อก",
    about: "เกี่ยวกับ",
    contact: "ติดต่อ",
    privacy: "ความเป็นส่วนตัว",
  },
  pl: {
    notepad: "Notatnik",
    writingTools: "Narzędzia do pisania",
    blog: "Blog",
    about: "O nas",
    contact: "Kontakt",
    privacy: "Prywatność",
  },
  nl: {
    notepad: "Notitieblok",
    writingTools: "Schrijftools",
    blog: "Blog",
    about: "Over",
    contact: "Contact",
    privacy: "Privacy",
  },
  sv: {
    notepad: "Anteckningsblock",
    writingTools: "Skrivverktyg",
    blog: "Blogg",
    about: "Om",
    contact: "Kontakt",
    privacy: "Sekretess",
  },
  el: {
    notepad: "Σημειωματάριο",
    writingTools: "Εργαλεία γραφής",
    blog: "Ιστολόγιο",
    about: "Σχετικά",
    contact: "Επικοινωνία",
    privacy: "Απόρρητο",
  },
  cs: {
    notepad: "Poznámkový blok",
    writingTools: "Nástroje pro psaní",
    blog: "Blog",
    about: "O nás",
    contact: "Kontakt",
    privacy: "Soukromí",
  },
  ro: {
    notepad: "Notepad",
    writingTools: "Instrumente de scriere",
    blog: "Blog",
    about: "Despre",
    contact: "Contact",
    privacy: "Confidențialitate",
  },
  hu: {
    notepad: "Jegyzettömb",
    writingTools: "Íróeszközök",
    blog: "Blog",
    about: "Rólunk",
    contact: "Kapcsolat",
    privacy: "Adatvédelem",
  },
  he: {
    notepad: "פנקס רשימות",
    writingTools: "כלי כתיבה",
    blog: "בלוג",
    about: "אודות",
    contact: "צור קשר",
    privacy: "פרטיות",
  },
  da: {
    notepad: "Notesblok",
    writingTools: "Skriveværktøjer",
    blog: "Blog",
    about: "Om",
    contact: "Kontakt",
    privacy: "Privatliv",
  },
  fi: {
    notepad: "Muistio",
    writingTools: "Kirjoitustyökalut",
    blog: "Blogi",
    about: "Tietoa",
    contact: "Yhteystiedot",
    privacy: "Tietosuoja",
  },
  no: {
    notepad: "Notatblokk",
    writingTools: "Skriveverktøy",
    blog: "Blogg",
    about: "Om",
    contact: "Kontakt",
    privacy: "Personvern",
  },
  sk: {
    notepad: "Poznámkový blok",
    writingTools: "Nástroje na písanie",
    blog: "Blog",
    about: "O nás",
    contact: "Kontakt",
    privacy: "Súkromie",
  },
  bg: {
    notepad: "Бележник",
    writingTools: "Инструменти за писане",
    blog: "Блог",
    about: "За нас",
    contact: "Контакт",
    privacy: "Поверителност",
  },
  hr: {
    notepad: "Bilježnica",
    writingTools: "Alati za pisanje",
    blog: "Blog",
    about: "O nama",
    contact: "Kontakt",
    privacy: "Privatnost",
  },
  sr: {
    notepad: "Beležnica",
    writingTools: "Alati za pisanje",
    blog: "Blog",
    about: "O nama",
    contact: "Kontakt",
    privacy: "Privatnost",
  },
  uk: {
    notepad: "Блокнот",
    writingTools: "Інструменти для письма",
    blog: "Блог",
    about: "Про нас",
    contact: "Контакт",
    privacy: "Конфіденційність",
  },
  ta: {
    notepad: "நோட்பேட்",
    writingTools: "எழுதும் கருவிகள்",
    blog: "வலைப்பதிவு",
    about: "எங்களை பற்றி",
    contact: "தொடர்பு",
    privacy: "தனியுரிமை",
  },
  te: {
    notepad: "నోట్‌ప్యాడ్",
    writingTools: "రచనా సాధనాలు",
    blog: "బ్లాగ్",
    about: "మా గురించి",
    contact: "సంప్రదించండి",
    privacy: "గోప్యత",
  },
  mr: {
    notepad: "नोटपॅड",
    writingTools: "लेखन साधने",
    blog: "ब्लॉग",
    about: "आमच्याबद्दल",
    contact: "संपर्क",
    privacy: "गोपनीयता",
  },
  gu: {
    notepad: "નોટપેડ",
    writingTools: "લખાણ સાધનો",
    blog: "બ્લોગ",
    about: "અમારા વિશે",
    contact: "સંપર્ક",
    privacy: "ગોપનીયતા",
  },
  kn: {
    notepad: "ನೋಟ್‌ಪ್ಯಾಡ್",
    writingTools: "ಬರವಣಿಗೆ ಸಾಧನಗಳು",
    blog: "ಬ್ಲಾಗ್",
    about: "ನಮ್ಮ ಬಗ್ಗೆ",
    contact: "ಸಂಪರ್ಕ",
    privacy: "ಗೌಪ್ಯತೆ",
  },
  ml: {
    notepad: "നോട്ട്പാഡ്",
    writingTools: "എഴുത്ത് ഉപകരണങ്ങൾ",
    blog: "ബ്ലോഗ്",
    about: "ഞങ്ങളെ കുറിച്ച്",
    contact: "ബന്ധപ്പെടുക",
    privacy: "സ്വകാര്യത",
  },
  si: {
    notepad: "නෝට්පෑඩ්",
    writingTools: "ලේඛන මෙවලම්",
    blog: "බ්ලොග්",
    about: "අප ගැන",
    contact: "සම්බන්ධ වන්න",
    privacy: "පෞද්ගලිකත්වය",
  },
  ne: {
    notepad: "नोटप्याड",
    writingTools: "लेखन उपकरणहरू",
    blog: "ब्लग",
    about: "हाम्रो बारेमा",
    contact: "सम्पर्क",
    privacy: "गोपनीयता",
  },
  my: {
    notepad: "နုတ်ပက်",
    writingTools: "ရေးသားရေးကိရိယာများ",
    blog: "ဘလော့ဂ်",
    about: "ကျွန်ုပ်တို့အကြောင်း",
    contact: "ဆက်သွယ်ရန်",
    privacy: "ကိုယ်ရေးကိုယ်တာ",
  },
  km: {
    notepad: "ណូតផេដ",
    writingTools: "ឧបករណ៍សរសេរ",
    blog: "ប្លុក",
    about: "អំពីយើង",
    contact: "ទំនាក់ទំនង",
    privacy: "ឯកជនភាព",
  },
  lo: {
    notepad: "ໂນ໊ດແພດ",
    writingTools: "ເຄື່ອງມືຂຽນ",
    blog: "ບລັອກ",
    about: "ກ່ຽວກັບ",
    contact: "ຕິດຕໍ່",
    privacy: "ຄວາມສ່ວນຕົວ",
  },
  mn: {
    notepad: "Тэмдэглэлийн дэвтэр",
    writingTools: "Бичих хэрэгслүүд",
    blog: "Блог",
    about: "Бидний тухай",
    contact: "Холбоо барих",
    privacy: "Нууцлал",
  },
  ka: {
    notepad: "ნოუთპადი",
    writingTools: "წერის ინსტრუმენტები",
    blog: "ბლოგი",
    about: "ჩვენ შესახებ",
    contact: "კონტაქტი",
    privacy: "კონფიდენციალურობა",
  },
  hy: {
    notepad: "Նոթատետր",
    writingTools: "Գրելու գործիքներ",
    blog: "Բլոգ",
    about: "Մեր մասին",
    contact: "Կապ",
    privacy: "Գաղտնիություն",
  },
  az: {
    notepad: "Notepad",
    writingTools: "Yazı alətləri",
    blog: "Bloq",
    about: "Haqqımızda",
    contact: "Əlaqə",
    privacy: "Məxfilik",
  },
  sw: {
    notepad: "Notepad",
    writingTools: "Zana za kuandika",
    blog: "Blogu",
    about: "Kuhusu",
    contact: "Mawasiliano",
    privacy: "Faragha",
  },
  zu: {
    notepad: "Notepad",
    writingTools: "Amathuluzi okubhala",
    blog: "Ibhulogi",
    about: "Mayelana",
    contact: "Xhumana",
    privacy: "Ubumfihlo",
  },
  af: {
    notepad: "Notaboek",
    writingTools: "Skryfgereedskap",
    blog: "Blog",
    about: "Oor",
    contact: "Kontak",
    privacy: "Privaatheid",
  },
  am: {
    notepad: "ኖትፓድ",
    writingTools: "የመጻፊያ መሳሪያዎች",
    blog: "ብሎግ",
    about: "ስለ እኛ",
    contact: "እውቂያ",
    privacy: "ግላዊነት",
  },
  so: {
    notepad: "Notepad",
    writingTools: "Qalabka qoraalka",
    blog: "Blog",
    about: "Ku saabsan",
    contact: "La xiriir",
    privacy: "Asturnaanta",
  },
  yo: {
    notepad: "Notepad",
    writingTools: "Awọn irinṣẹ kikọ",
    blog: "Bulọọgi",
    about: "Nipa wa",
    contact: "Kan si",
    privacy: "Asiri",
  },
  ig: {
    notepad: "Notepad",
    writingTools: "Ngwa ide",
    blog: "Blog",
    about: "Banyere",
    contact: "Kpọtụrụ",
    privacy: "Nzuzo",
  },
  ha: {
    notepad: "Notepad",
    writingTools: "Kayan rubutu",
    blog: "Blog",
    about: "Game da",
    contact: "Tuntuɓa",
    privacy: "Sirri",
  },
  mg: {
    notepad: "Notepad",
    writingTools: "Fitaovana fanoratana",
    blog: "Bilaogy",
    about: "Momba",
    contact: "Fifandraisana",
    privacy: "Tsiambaratelo",
  },
  uz: {
    notepad: "Notepad",
    writingTools: "Yozish vositalari",
    blog: "Blog",
    about: "Haqida",
    contact: "Aloqa",
    privacy: "Maxfiylik",
  },
  kk: {
    notepad: "Блокнот",
    writingTools: "Жазу құралдары",
    blog: "Блог",
    about: "Біз туралы",
    contact: "Байланыс",
    privacy: "Құпиялылық",
  },
  ky: {
    notepad: "Блокнот",
    writingTools: "Жазуу куралдары",
    blog: "Блог",
    about: "Биз жөнүндө",
    contact: "Байланыш",
    privacy: "Купуялуулук",
  },
  tg: {
    notepad: "Дафтарча",
    writingTools: "Асбобҳои навиштан",
    blog: "Блог",
    about: "Дар бораи мо",
    contact: "Тамос",
    privacy: "Махфият",
  },
  tk: {
    notepad: "Bloknot",
    writingTools: "Ýazuw gurallary",
    blog: "Blog",
    about: "Biz barada",
    contact: "Habarlaşmak",
    privacy: "Gizlinlik",
  },
  ps: {
    notepad: "نوټ پیډ",
    writingTools: "د لیکلو وسایل",
    blog: "بلاګ",
    about: "زموږ په اړه",
    contact: "اړیکه",
    privacy: "محرمیت",
  },
  ku: {
    notepad: "Notepad",
    writingTools: "Amûrên nivîsandin",
    blog: "Blog",
    about: "Derbarê",
    contact: "Têkilî",
    privacy: "Taybetî",
  },
  sq: {
    notepad: "Notepad",
    writingTools: "Mjete shkrimi",
    blog: "Blog",
    about: "Rreth nesh",
    contact: "Kontakt",
    privacy: "Privatësi",
  },
  lt: {
    notepad: "Užrašų knygelė",
    writingTools: "Rašymo įrankiai",
    blog: "Tinklaraštis",
    about: "Apie mus",
    contact: "Kontaktai",
    privacy: "Privatumas",
  },
  lv: {
    notepad: "Piezīmju bloks",
    writingTools: "Rakstīšanas rīki",
    blog: "Blogs",
    about: "Par mums",
    contact: "Kontakti",
    privacy: "Privātums",
  },
  et: {
    notepad: "Märkmik",
    writingTools: "Kirjutamise tööriistad",
    blog: "Blogi",
    about: "Meist",
    contact: "Kontakt",
    privacy: "Privaatsus",
  },
  is: {
    notepad: "Minnisbók",
    writingTools: "Skrifverkfæri",
    blog: "Blogg",
    about: "Um okkur",
    contact: "Hafa samband",
    privacy: "Persónuvernd",
  },
  ga: {
    notepad: "Leabhar nótaí",
    writingTools: "Uirlisí scríbhneoireachta",
    blog: "Blag",
    about: "Fúinn",
    contact: "Teagmháil",
    privacy: "Príobháideachas",
  },
  cy: {
    notepad: "Llyfr nodiadau",
    writingTools: "Offer ysgrifennu",
    blog: "Blog",
    about: "Amdanom ni",
    contact: "Cyswllt",
    privacy: "Preifatrwydd",
  },
  eu: {
    notepad: "Koadernoa",
    writingTools: "Idazteko tresnak",
    blog: "Bloga",
    about: "Guri buruz",
    contact: "Harremana",
    privacy: "Pribatutasuna",
  },
  ca: {
    notepad: "Bloc de notes",
    writingTools: "Eines d’escriptura",
    blog: "Blog",
    about: "Sobre nosaltres",
    contact: "Contacte",
    privacy: "Privacitat",
  },
  gl: {
    notepad: "Caderno de notas",
    writingTools: "Ferramentas de escritura",
    blog: "Blog",
    about: "Sobre nós",
    contact: "Contacto",
    privacy: "Privacidade",
  },
  mt: {
    notepad: "Notepad",
    writingTools: "Għodod tal-kitba",
    blog: "Blog",
    about: "Dwarna",
    contact: "Kuntatt",
    privacy: "Privatezza",
  },
  lb: {
    notepad: "Notizblock",
    writingTools: "Schreifwierkzeugen",
    blog: "Blog",
    about: "Iwwer eis",
    contact: "Kontakt",
    privacy: "Privatsphär",
  },
  mk: {
    notepad: "Бележник",
    writingTools: "Алатки за пишување",
    blog: "Блог",
    about: "За нас",
    contact: "Контакт",
    privacy: "Приватност",
  },
  bs: {
    notepad: "Bilježnica",
    writingTools: "Alati za pisanje",
    blog: "Blog",
    about: "O nama",
    contact: "Kontakt",
    privacy: "Privatnost",
  },
  sl: {
    notepad: "Beležnica",
    writingTools: "Orodja za pisanje",
    blog: "Blog",
    about: "O nas",
    contact: "Kontakt",
    privacy: "Zasebnost",
  },
  fj: {
    notepad: "Notepad",
    writingTools: "iYaya ni volavola",
    blog: "Blog",
    about: "Baleti keitou",
    contact: "Veitaratara",
    privacy: "Tawase ni itukutuku",
  },
  mi: {
    notepad: "Pukatuhi",
    writingTools: "Ngā taputapu tuhituhi",
    blog: "Blog",
    about: "Mō mātou",
    contact: "Whakapā",
    privacy: "Tūmataiti",
  },
  sm: {
    notepad: "Notepad",
    writingTools: "Meafaigaluega tusitusi",
    blog: "Blog",
    about: "E uiga ia i matou",
    contact: "Fesoʻotaʻi",
    privacy: "Fa’alilolilo",
  },
  to: {
    notepad: "Notepad",
    writingTools: "Ngaahi me’angaue tohi",
    blog: "Blog",
    about: "Fekau’aki mo kimautolu",
    contact: "Fetu’utaki",
    privacy: "Fakapulipuli",
  },
  ht: {
    notepad: "Notepad",
    writingTools: "Zouti ekriti",
    blog: "Blog",
    about: "Sou nou",
    contact: "Kontak",
    privacy: "Konfidansyalite",
  },
  qu: {
    notepad: "Qillqana",
    writingTools: "Qillqay yanapakuykuna",
    blog: "Blog",
    about: "Ñuqanchikmanta",
    contact: "Tupachiy",
    privacy: "Pakay",
  },
  ay: {
    notepad: "Qillqaña",
    writingTools: "Qillqaña yänaka",
    blog: "Blog",
    about: "Jiwasanakat",
    contact: "Aruskipañataki",
    privacy: "Imantata",
  },
  gn: {
    notepad: "Kuatiahaipyre",
    writingTools: "Tembiporu jehaipyre",
    blog: "Blog",
    about: "Ore rehegua",
    contact: "Ñe’ẽndy",
    privacy: "Ñemigua",
  },
  nv: {
    notepad: "Naaltsoos",
    writingTools: "Ákót’éego yáhoot’ééł",
    blog: "Blog",
    about: "Nihí baa hane’",
    contact: "K’ad doo",
    privacy: "Diné binahjį’",
  },
  iu: {
    notepad: "ᓄᑕᕋᖅ",
    writingTools: "ᑎᑎᖅᑲᓕᕆᔨᑦ",
    blog: "ᑕᑯᓇᒐᓗᐊᖅ",
    about: "ᒥᒃᓴᐅᓂᖅ",
    contact: "ᐊᐃᑦᑐᖅ",
    privacy: "ᑭᒥᑦᑐᖅ",
  },
  kl: {
    notepad: "Allattuut",
    writingTools: "Allannermut atortut",
    blog: "Blog",
    about: "Uagut pillugit",
    contact: "Attavigiuk",
    privacy: "Isertuussineq",
  },
  om: {
    notepad: "Barreessituu",
    writingTools: "Meeshaalee barreessuu",
    blog: "Blog",
    about: "Waa’ee keenya",
    contact: "Quunnamtii",
    privacy: "Icciitii",
  },
  ti: {
    notepad: "ኖትፓድ",
    writingTools: "መሳርሒ ጽሑፍ",
    blog: "ብሎግ",
    about: "ብዛዕባና",
    contact: "ርክብ",
    privacy: "ምስጢር",
  },
  sn: {
    notepad: "Notepad",
    writingTools: "Zvishandiso zvekanyora",
    blog: "Blog",
    about: "Nezvedu",
    contact: "Bata nesu",
    privacy: "Chakavanzika",
  },
  xh: {
    notepad: "Notepad",
    writingTools: "Izixhobo zokubhala",
    blog: "Blog",
    about: "Ngathi",
    contact: "Qhagamshelana",
    privacy: "Ubumfihlo",
  },
  ceb: {
    notepad: "Notepad",
    writingTools: "Mga himan sa pagsulat",
    blog: "Blog",
    about: "Mahitungod",
    contact: "Kontak",
    privacy: "Pribasiya",
  },
  tl: {
    notepad: "Notepad",
    writingTools: "Mga kasangkapan sa pagsulat",
    blog: "Blog",
    about: "Tungkol sa amin",
    contact: "Makipag-ugnayan",
    privacy: "Pagkapribado",
  },
  jv: {
    notepad: "Notepad",
    writingTools: "Piranti nulis",
    blog: "Blog",
    about: "Babagan kita",
    contact: "Kontak",
    privacy: "Privasi",
  },
  su: {
    notepad: "Notepad",
    writingTools: "Alat nulis",
    blog: "Blog",
    about: "Ngeunaan kami",
    contact: "Kontak",
    privacy: "Privasi",
  },
};

export function getNavLabels(locale: string): NavLabels {
  return byLocale[locale] ?? en;
}
