import type { LucideIcon } from "lucide-react";
import {
  Timer,
  FileCode,
  Target,
  Mic,
  Eraser,
  GitCompare,
  LayoutTemplate,
  Library,
  BookOpen,
  Printer,
  Share2,
  FolderInput,
  Download,
  Keyboard,
  Code2,
  Braces,
  FileCode2,
  Type,
  CaseSensitive,
  ListOrdered,
  Pilcrow,
  Clock,
  CaseUpper,
  RemoveFormatting,
  CopyMinus,
  ArrowDownAZ,
  FileDiff,
  Wand2,
  Minimize2,
  Paintbrush,
  Binary,
  Link2,
  Regex,
  CodeXml,
  FileSpreadsheet,
  FileType2,
  FileOutput,
} from "lucide-react";
import type { WritingToolId } from "@/lib/writing-tools-registry";

const ICON_MAP: Record<WritingToolId, LucideIcon> = {
  "markdown-notepad": FileCode,
  "code-notepad": Code2,
  "json-editor": Braces,
  "html-editor": FileCode2,
  "word-counter": Type,
  "character-counter": CaseSensitive,
  "sentence-counter": ListOrdered,
  "paragraph-counter": Pilcrow,
  "reading-time-calculator": Clock,
  "case-converter": CaseUpper,
  "text-cleaner": RemoveFormatting,
  "duplicate-remover": CopyMinus,
  "text-sorter": ArrowDownAZ,
  "text-compare-diff": FileDiff,
  "json-formatter": Wand2,
  "html-minifier": Minimize2,
  "css-beautifier": Paintbrush,
  "base64-codec": Binary,
  "url-codec": Link2,
  "regex-tester": Regex,
  "xml-formatter": CodeXml,
  "focus-timer": Timer,
  "goal-tracker": Target,
  "speech-dictation": Mic,
  "paste-clean": Eraser,
  "compare-drafts": GitCompare,
  templates: LayoutTemplate,
  "snippet-shelf": Library,
  "reading-mode": BookOpen,
  "print-note": Printer,
  "share-note": Share2,
  "import-export": FolderInput,
  "install-app": Download,
  "keyboard-shortcuts": Keyboard,
  "text-to-excel": FileSpreadsheet,
  "csv-to-excel": FileSpreadsheet,
  "json-to-excel": FileSpreadsheet,
  "xml-to-excel": FileSpreadsheet,
  "html-to-excel": FileSpreadsheet,
  "pdf-to-excel": FileSpreadsheet,
  "excel-to-csv": FileSpreadsheet,
  "excel-to-json": FileSpreadsheet,
  "excel-to-xml": FileSpreadsheet,
  "excel-to-pdf": FileSpreadsheet,
  "google-sheet-to-excel": FileSpreadsheet,
  "numbers-to-excel": FileSpreadsheet,
  "ods-to-excel": FileSpreadsheet,
  "excel-to-ods": FileSpreadsheet,
  "excel-to-google-sheet": FileSpreadsheet,
  "pdf-to-word": FileType2,
  "word-to-pdf": FileType2,
  "text-to-pdf": FileType2,
  "pdf-to-text": FileType2,
  "word-to-txt": FileType2,
  "txt-to-word": FileType2,
  "html-to-pdf": FileType2,
  "pdf-to-html": FileType2,
  "markdown-to-pdf": FileType2,
  "pdf-to-markdown": FileType2,
  "ppt-to-pdf": FileType2,
  "pdf-to-ppt": FileType2,
  "rtf-to-pdf": FileType2,
  "pdf-to-rtf": FileType2,
  "txt-to-markdown": FileType2,
  "markdown-to-txt": FileType2,
  "html-to-word": FileType2,
  "word-to-html": FileType2,
  "json-to-csv": FileOutput,
  "csv-to-json": FileOutput,
  "json-to-xml": FileOutput,
  "xml-to-json": FileOutput,
  "yaml-to-json": FileOutput,
  "json-to-yaml": FileOutput,
  "sql-to-csv": FileOutput,
  "csv-to-sql": FileOutput,
  "text-to-json": FileOutput,
  "json-to-text": FileOutput,
  "text-to-xml": FileOutput,
  "xml-to-text": FileOutput,
  "text-uppercase-lowercase": CaseUpper,
  "text-to-camel-case": CaseUpper,
  "text-to-snake-case": CaseUpper,
  "text-to-kebab-case": CaseUpper,
  "split-text-to-columns": ListOrdered,
  "merge-text-lines": ListOrdered,
  "convert-line-endings": ListOrdered,
  "minify-json": Minimize2,
  "minify-xml": Minimize2,
};

export function ToolIcon({
  id,
  className,
}: {
  id: WritingToolId;
  className?: string;
}) {
  const I = ICON_MAP[id];
  if (!I) return null;
  return <I className={className} aria-hidden />;
}
